### ISSUE TITLE
Feature Request: Cables connect terminal to multiple inventories

### ISSUE THREAD

**Issue by erisdev** [tom5454/Toms-Storage#1]
I was surprised & disappointed that a setup like this doesn't grant access to all three barrels, like most other networked storage systems do.

![2020-06-04_20 17 34](https://user-images.githubusercontent.com/143007/83822936-bc6cc300-a68f-11ea-9e75-e4183dcb97e7.png)

I like the simplicity of this mod, but the fact that there are several blocks that seem to connect inventories in slightly different ways is a little confusing. It would be nice to unify those connection features under one thing: cables.

**Comment by tom5454** [comment]
The inventory cables are designed for long range one to one connections. Use the Inventory Connector and Inventory Trims to connect them like this.

**Comment by erisdev** [comment]
I guess in that case it'd be nice to have some indication of that in game. I was pretty confused by it.
