### ISSUE TITLE
1.18.2 modded fabric server, it crashes

### ISSUE THREAD

**Issue by linkydee** [tom5454/Toms-Storage#100]
[crash-2022-05-18_16.47.08-server.txt](https://github.com/tom5454/Toms-Storage/files/8718421/crash-2022-05-18_16.47.08-server.txt)
This is the crash report given

**Comment by tom5454** [comment]
Some other mod's mixin is crashing, `forcedEnchantments$mapToNbtList`. Please report it to [ForceEnchantments](https://github.com/biom4st3r/ForceEnchantments).
