### ISSUE TITLE
Beacons don't extend advanced wireless terminal range

### ISSUE THREAD

**Issue by Fuegofandango** [tom5454/Toms-Storage#102]
Using 1.16.5 version. I've put a level 1 and 2 beacon directly next to a inventory connector and terminal and it still refuses to extend the range. Is this not a feature in the 1.16.5 version?

**Comment by tom5454** [comment]
Thats not a feature on 1.16

**Comment by rauenzi** [comment]
Is this a feature in the 1.17 version, or was this exclusive to 1.18?

**Comment by tom5454** [comment]
Exclusive to the 1.3.0+ versions on 1.18.2
