### ISSUE TITLE
Storage network not detecting Expanded Storage Iron Chests as inventories

### ISSUE THREAD

**Issue by G93d14** [tom5454/Toms-Storage#106]
![2022-06-02_12 43 13](https://user-images.githubusercontent.com/54314688/171574181-3f663b5c-f180-4654-a344-be5cc105f9d2.png)

![2022-06-02_12 44 39](https://user-images.githubusercontent.com/54314688/171574406-271d8cdd-f886-498b-a5c9-d7a9e33c3ca6.png)

![2022-06-02_12 43 21](https://user-images.githubusercontent.com/54314688/171574195-bedd43cc-15a8-4284-a890-e38925aa94dd.png)

as you can see my inventories aren't being detected. is this a conflict with your mods or is it something I need to correct on my side?

**Comment by G93d14** [comment]
I've also posted a report at the Expanded Storage GitHub page in case the issue is on their end.

**Comment by InstructorJason** [comment]
I'm using them now in 1.19.  If you use an inventory connector they do work.  Just be aware that if you create double chests the counts will be doubled.

**Comment by tom5454** [comment]
This sould be fixed in 1.4.2
