### ISSUE TITLE
Config not working.

### ISSUE THREAD

**Issue by ImTheGoose** [tom5454/Toms-Storage#107]
when i edit the config file. like changing advanced wireless terminal distance. it just resets when the server start. 

Fabric 1.17.1 (newest for 1.17.1)
Tomsstorage-1.1.18.jar

**Comment by ImTheGoose** [comment]
Update: ive tested a bit more turns out it works fine up to 512 blocks. i dont know why but it wont let me change it to 1024 or anything above. why is this cap there

**Comment by tom5454** [comment]
The wireless terminal has an upper limit of 512 blocks.
