### ISSUE TITLE
REI - Crafting Terminal does not recognize multiple ingredients

### ISSUE THREAD

**Issue by aNinjin** [tom5454/Toms-Storage#110]
The crafting terminal isn't able to pull different ingredients when pressing [+] to pull down. It will only pull down what it is showing. I honestly thought it was REI but it also seems to be an issue with JEI as well. I tested it with a regular crafting table and even refined storage and Tom's is the only one that isn't able to do so. A picture of what I'm talking about(crafting a storage terminal for show):
![Screenshot 2022-06-10 195752](https://user-images.githubusercontent.com/106577745/173170175-ef84a3d5-d58f-49e4-80b0-77c09354e68b.png)

**Comment by tom5454** [comment]
Fixed in latest releases
