### ISSUE TITLE
Inventory Proxy will not insert into top slot of Brewing Stand

### ISSUE THREAD

**Issue by trunksbomb** [tom5454/Toms-Storage#118]
Minecraft 1.18.2
Fabric 0.14.6
Tom's version 1.3.2

![image](https://user-images.githubusercontent.com/1904331/177857669-e7624114-a4c8-4b62-9245-cb3845e0e480.png)

The left side of this does not work. Basic Inventory Hopper -> Proxy (with or without filter) -> Brewing Stand (top face)
The right side does. Basic Inventory Hopper -> Brewing Stand (top face)

I can use the setup on the left to put a single Blaze Powder into the Brewing Stand from the sides. So proxies appear to work in some conditions with the brewing stand, it's just that they won't insert into the top for whatever reason.

If I swap the brewing stand for a chest or a hopper, it starts to fill it up with my specified ingredient.

Also to note, the proxy does detect the brewing stand below it because the in-world tooltip from "What the hell is that?" mod shows the contents of the brewing stand when I look at the proxy.

**Comment by tom5454** [comment]
The inventory proxy filtering doesn't work on fabric due to how the fabric inventory api works.
