### ISSUE TITLE
Issues connecting to inventories from other mods

### ISSUE THREAD

**Issue by Sammcb** [tom5454/Toms-Storage#120]
I'm using v1.3.4 for Fabric on Minecraft 1.18.2. I have the [Extended Drawers](https://modrinth.com/mod/extended-drawers) mod installed was trying to get the Inventory Connector to work and can't seem to connect to either a Drawer or Drawer Access Point. Extended Drawers Access Point works with similar mods like [Slotlink](https://modrinth.com/mod/slotlink) so I think it is an issue with this mod.

**Comment by tom5454** [comment]
Should work in the latest version 1.4.2
