### ISSUE TITLE
Items in terminal showing double the amount put in using double chests in the expanded storage mod

### ISSUE THREAD

**Issue by aiicarus** [tom5454/Toms-Storage#121]
I have a bug with this mod's interaction with fabric expanded storage. Whenever I make a double chest with a non-vanilla chest that connects to a storage system any item I put into the system shows up as double the amount I put in. So if I have a double iron chest connected to the system and I put in a stack of stone it shows up as 128 in the terminal visually, while the actual amount still remains as 64. Any time I take it out the amount of stone is 64 just it shows visually as 128 in the terminal.

**Comment by RSpyno** [comment]
Same problem with the Iron Chests mod

**Comment by tom5454** [comment]
Should be fixed in the latest version 1.4.2
