### ISSUE TITLE
[1.18] Dank storage not connecting

### ISSUE THREAD

**Issue by CyberFoxar** [tom5454/Toms-Storage#131]
Probably related to #120 but including it for completness.
I'm using version 1.3.0 backported to 1.18 in a modpack (DreamCraft v12).

Using a [dank storage](https://www.curseforge.com/minecraft/mc-mods/dank-storage-fabric)'s dock does not work with either an inventory connector or InventoryCableConnector. Since it interface properly with other mods such as slotlink and applied Energetics, I figure it's an issue with how your mod is setup.

I am currently unable to see if this behavior also happens in 1.19 version of your mod.

Thanks.

**Comment by tom5454** [comment]
Should work in the latest version 1.4.2
