### ISSUE TITLE
[Fabric] [1.18.2] Does not work with Item Vault from Create

### ISSUE THREAD

**Issue by ArsenicPurple** [tom5454/Toms-Storage#132]
It's works in the forge version so I assume it's a Fabric thing or it could be on Creates side.

**Comment by JustFalcon** [comment]
This is still not fixed I believe? Even with Fabric Transfer API added.

**Comment by JustFalcon** [comment]
> The Transfer API was only added for 1.19, create isn't on 1.19 yet. (I'll close this issue once create updates and I can test it.)

Is it possible to/will you backport that change to 1.18?

**Comment by pikasalt** [comment]
As of 1.4.1, Item vaults will now connect to the storage systems. However, the terminals display multiplies the amount of items shown by how many vault blocks are placed. This does not actually duplicate items, just how they're counted in the terminal.
