### ISSUE TITLE
Is the intended?

### ISSUE THREAD

**Issue by nEONcReepER990** [tom5454/Toms-Storage#137]
![2022-08-21_09 39 38](https://user-images.githubusercontent.com/95697642/185781018-5063ee56-3689-4443-853b-bf77b1ba6213.png)

I am on Fabric 1.19

**Comment by tom5454** [comment]
Thats a warning item if a loop is detected, you can't take these items out, it's visual only.

**Comment by nEONcReepER990** [comment]
Ok, but wheres the loop? if there is only 2 connectors and 2 proxys, thats what i ment, sorry for not saying it at first.
