### ISSUE TITLE
[Fabric 1.18.2] Items in Expanded Storage Double chests connected by inventory trims appear doubled

### ISSUE THREAD

**Issue by PhoenixEvolver** [tom5454/Toms-Storage#140]
https://youtu.be/l-TOe2uf97o

A visual bug occurs when connecting upgraded double chests from Expanded Storage to an inventory connector using Inventory trims. When displayed through the storage terminal, the number of items in the Inventory trim storage network appears doubled. This does not seem to be the case for the same kinds of double chests connected through inventory cables.

**Comment by tom5454** [comment]
Should be fixed in 1.4.2
