### ISSUE TITLE
JEI sync search doesn't include @

### ISSUE THREAD

**Issue by generikb** [tom5454/Toms-Storage#141]
Hello!

I'm putting together a 1.18.2 modpack with Tom's Simple Storage, and I'm having trouble with the search bar.  As you can see in the screenshot, if I try to type "@create" in Tom's, it only shows "create" in JEI, without the @.  

And if I try to type "@create" in JEI, the first @ doesn't register, so I have to type it twice...so then it's "@create" in JEI but "@@create" in Tom's!  Very strange

![image](https://user-images.githubusercontent.com/41623747/188289949-0203fb0a-c57e-47fe-946d-a5c3d384c7e5.png)

**Comment by generikb** [comment]
2nd screenshot to show the "@@create" situation I mentioned.  I've tried all the different search modes in Tom's and they all seem to not work.

![image](https://user-images.githubusercontent.com/41623747/188290021-6797d3f7-3bcf-4969-8446-90b8b1d8f2d5.png)

**Comment by JoelZBub** [comment]
Let me help this poor fella out a bit, bless his pea pickin little heart.
Forge version: 40.1.73
JEI version: 1.18.2-forge-10.1.3.240
Tom's Storage version: 1.18.2-1.3.4
