### ISSUE TITLE
Urgent dupe glitch with Traveler's Backpack mod

### ISSUE THREAD

**Issue by chorbintime** [tom5454/Toms-Storage#144]
https://github.com/LunaPixelStudios/Medieval-MC/issues/329
 
 This issue was posted on our modpack's github page today. Basically, when a backpack from the Traveler's Backpack mod is combined with shears in a crafting terminal, the backpack and its contents are duplicated, as seen here: https://www.twitch.tv/mtijger/clip/HedonisticFrailSwallowPJSalt-Wj79BjvSvoCg62Px

**Comment by tom5454** [comment]
Duplicate of #142
