### ISSUE TITLE
Cant type into EMI search bar while terminal is open

### ISSUE THREAD

**Issue by CodeF53** [tom5454/Toms-Storage#145]
## steps to reproduce:
1. download [EMI](https://modrinth.com/mod/emi) and Toms-Storage
2. make a functional crafting/storage terminal setup
3. open the crafting/storage terminal 
4. click into EMI's search bar on the bottom
5. try to type.

## Expected behavior
- keys pressed go into EMI's search bar
## Actual behavior
- all input goes into crafting/storage terminal 

## Video demonstrating behavior:

https://user-images.githubusercontent.com/37855219/188782917-de5618fc-c530-489b-b1d2-568bde14886a.mp4

**Comment by tom5454** [comment]
This is a bug with the emi search bar, it breaks with the anvil gui and the create search tab as well.

**Comment by ryleu** [comment]
![image](https://user-images.githubusercontent.com/69326171/213795857-a6aa854f-3b8e-4228-86a9-005ee16edae4.png)
works on my machine

are you using forge?
