### ISSUE TITLE
crafting terminal "doesnt recognize recipe" - EMI incompatibility

### ISSUE THREAD

**Issue by CodeF53** [tom5454/Toms-Storage#146]
## steps to reproduce:
1. download [EMI](https://modrinth.com/mod/emi) and Toms-Storage
2. make a functional crafting terminal setup
3. open the crafting terminal 
4. click any item craftable with a normal crafting table in EMI
5. try to click the "add recipe to table" button

## expected behavior:
items go into the the crafting terminal
## actual behavior:
EMI says "current workstation does not support recipe"
## video demonstrating behavior:

https://user-images.githubusercontent.com/37855219/188783366-348f4003-64ed-4ad7-9e77-0474911c84f3.mp4

**Comment by cTurtle98** [comment]
i see this as well

**Comment by tom5454** [comment]
Implemented in 1.4.5 for Minecraft 1.19+
