### ISSUE TITLE
Ticking entity crash when opening terminal

### ISSUE THREAD

**Issue by iCubedPH** [tom5454/Toms-Storage#154]
Description: Ticking entity
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
[crash-2022-10-03_10.40.30-server.txt](https://github.com/tom5454/Toms-Storage/files/9696857/crash-2022-10-03_10.40.30-server.txt)

**Comment by tommybdl89** [comment]
i have the same problem

**Comment by Masuary** [comment]
Same problem using 1.4.3
