### ISSUE TITLE
Advancements

### ISSUE THREAD

**Issue by joseth257** [tom5454/Toms-Storage#16]
Advancements for recipe-unlock are appearing on the advancements page. Just three "black sections", with a respective icon only, no title, no background, etc. (easily reproducible by creating a world and granting an user all advancements by command)

The solution I have seem around is that for advancements related to recipe unlock only, the section "display":{...} should not be included. Doing so will hide those glitches sections, avoiding the small inconvenience for the users.

This does not affect game-play. And can be fixed in the user side by simple replacing the respective files in a datapack.

**Comment by InsaanNotFound** [comment]
Might i ask for a datapack to fix it? 
Also here are screenshots
![2020-12-16_18 40 09](https://user-images.githubusercontent.com/69729089/102385625-5f52b200-3fce-11eb-88d5-07ed5ebf84d0.png)
![2020-12-16_18 40 13](https://user-images.githubusercontent.com/69729089/102385631-624da280-3fce-11eb-9ab8-a92483b62086.png)
![2020-12-16_18 40 17](https://user-images.githubusercontent.com/69729089/102385641-64affc80-3fce-11eb-8673-c2681481e094.png)

**Comment by joseth257** [comment]
@InsaanNotFound here is what i am using. 
[toms-storage-fix.zip](https://github.com/tom5454/Toms-Storage/files/5706028/toms-storage-fix.zip)
