### ISSUE TITLE
Basic wireless terminal won't connect [Fabric 1.19 v1.4.3]

### ISSUE THREAD

**Issue by DerpyFrood0421** [tom5454/Toms-Storage#160]
Hi. Using the 1.4.3 [Fabric] release of Tom's for 1.19.  Unable to bind the basic wireless terminal to the crafting terminal, so it doesn't work (even from one block away). Tested with advanced terminal and that does work, so I think the issue is specific to the basic wireless terminal.

**Comment by tom5454** [comment]
The basic wireless terminal can't bind to a block, it only extends your reach while looking at a terminal, use the advanced variant.

**Comment by aelfwyne** [comment]
> The basic wireless terminal can't bind to a block, it only extends your reach while looking at a terminal, use the advanced variant.

Oh.. that's pretty stupid. Maybe update the description to point this out that it's not "actually" wireless?
