### ISSUE TITLE
[1.19.2] Can't access Item via terminal

### ISSUE THREAD

**Issue by ffuentesm** [tom5454/Toms-Storage#164]
Tom's: 1.3.9
FOrge: 43.1.57
Minecraft: 1.19.2
Ars: 3.4.6
For some reason, I can't access Warp Scrolls from terminals. I can see them, but I can not pick them up via the terminal. 
if I open the container they are in, I can pick them up, but not via the mod's terminal. 
![image](https://user-images.githubusercontent.com/44974827/201450299-44d6e184-d5e1-40f3-b056-c88121a7a571.png)

**Comment by MUYUTwilighter** [comment]
Same problem on my side :(
MOD: 1.2.19
Forge: 36.2.34
Minecraft: 1.16.5
Some items can be taken out (like ironchest:iron_chest), while others can not (like minecraft:cooked_portchop).

**Comment by MUYUTwilighter** [comment]
> Same problem on my side :( MOD: 1.2.19 Forge: 36.2.34 Minecraft: 1.16.5 Some items can be taken out (like ironchest:iron_chest), while others can not (like minecraft:cooked_portchop).

Here's download link of the modpack I was playing. This is packed by myself and I didn't do any modifications.
https://pan.baidu.com/s/1wmZqrOkJ7zSjIRYs1nAl-w?pwd=muyu
