### ISSUE TITLE
(1.19) Can't pull Items out of inventory

### ISSUE THREAD

**Issue by slivers34** [tom5454/Toms-Storage#170]
Im playing a custome modpack(1.19.2), with lots of mods and im trying to combine Tom's storage (1.3.9) with a Modular Storage from RFTools, Problem is i cant take some items out of the storage when using the crafting terminal.

**Comment by ffuentesm** [comment]
I posted the same issue earlier 
https://github.com/tom5454/Toms-Storage/issues/164
I can see the item in the terminal but I can not pull it out. 
I need to find the item inside the chest to get it out manually.
