### ISSUE TITLE
Dupe issue on Latest Fabric Version

### ISSUE THREAD

**Issue by xSHXRKIEx** [tom5454/Toms-Storage#171]
I see that #153  was closed but the dupe still occurs on latest toms_storage_fabric-1.19-1.4.4.jar
Here is a video showing you that you can easily dupe items. Basically you just shift click items in and shift click items out and it eventually starts duping.

https://clipchamp.com/watch/12Wpapt7D89

**Comment by tom5454** [comment]
Fixed in 1.4.5
