### ISSUE TITLE
Creative inventory and JEI 

### ISSUE THREAD

**Issue by Dinocraft1515YT** [tom5454/Toms-Storage#172]
**Describe the bug**
The items of this mod don't appear in the creative inventory and JEI

**To Reproduce**
I don't know how it happen

**Video**
https://clipchamp.com/watch/Gu6ILKJGxtm

**Versions (please complete the following information):**
 - Fabric Loader Version: 0.4.11
 - MC Version: 1.19.2
 - Mod Version: 1.4.4
 - JEI Version (if present) : 11.4.0.287
 - Fabric API Version (if present) : 0.68.0

**Comment by tom5454** [comment]
Also buy the game

**Comment by Dinocraft1515YT** [comment]
> Please post your minecraft log

[2022-12-09-3.log.gz](https://github.com/tom5454/Toms-Storage/files/10200328/2022-12-09-3.log.gz)

**Comment by Dinocraft1515YT** [comment]
> Also buy the game

What if I can't, because I'm poor -_-
