### ISSUE TITLE
[FABRIC 1.19.2] Huge lag spikes while using Crafting Terminal with Recipe Book

### ISSUE THREAD

**Issue by jmadarg** [tom5454/Toms-Storage#182]
***Modpack:*** Better MC [FABRIC] - BMC1 v12.5

***MC Version:*** Fabric 1.19.2

***Mod Version:*** 1.4.3

***Issue:*** When using the Crafting Terminal with the Recipe Book open there is a bunch of lag spikes while moving items and/or crafting.

***Steps to reproduce:***
1. Create a new instance of BMC1 Fabric
2. Create a new world
3. Build a simple storage system, like this one:

![image](https://user-images.githubusercontent.com/62086445/210129730-7d011c56-6095-4c75-b67b-01c69dba8794.png)

4. Place some items (for example cobble) in the system
5. Unlock recipes by using `/recipe give @a *` (I did this one because it seems to be worse the more recipes are unlocked)
6. Open the crafting terminal and compare the performance between having the Recipe Book open/closed while moving items or crafting
7. While using Alt+f3 you can probably see similar results to these:

![image](https://user-images.githubusercontent.com/62086445/210129879-230bed1f-5341-4baf-9291-8d33eea1bbcf.png)

![image](https://user-images.githubusercontent.com/62086445/210129863-1b69b948-3d63-4fdb-b8f1-83b0f96be494.png)

***Extra Data:***
I ran Spark profilers for ticks over 50, 100 and 150 ms while moving items and crafting. 

**Book Open:**
Ticks over 150 https://spark.lucko.me/P4mcxLzvPA
Ticks over 100 https://spark.lucko.me/92vsWBBGhQ
Ticks over 50   https://spark.lucko.me/RuS4VdjgSu

**Book Closed:**
Ticks over 150 https://spark.lucko.me/xRg01aqJvW
Ticks over 100 https://spark.lucko.me/RxbN0jE0L2
Ticks over 50   https://spark.lucko.me/hlRnnDNu3r

Even though the amount of ticks over those limits of the 2 cases are pretty similar, when the book is closed everything feels way smother.

The command used for the profilers was `/spark profiler --only-ticks-over x`, where `x` is the amount of milliseconds.

***Does it change with a more up-to-date version of the mod?***
Haven't done any exhaustive testing (haven't run profilers nor the simple Alt+F3 visual test), but performance feels the same.

**Comment by SHXRKIIE** [comment]
its an issue with WilderWild Mod and was removed in the latest BMC update
