### ISSUE TITLE
Functional Storage Wrong item count Display

### ISSUE THREAD

**Issue by ffuentesm** [tom5454/Toms-Storage#185]
When I have an Inventory Connector near a Drawer Controller. The item count is checked twice. 
As the connector reads it once, then the controller reads it a second time due to the drawers being near each other. 
![image](https://user-images.githubusercontent.com/44974827/213790258-161ae19a-c969-47a5-8a85-cf7ebd236a11.png)
![image](https://user-images.githubusercontent.com/44974827/213790308-7b3d4c7e-97bf-4edc-87a9-3c6295c7eafa.png)

**Comment by katubug** [comment]
This also occurs with Storage Drawers.

**Comment by SirGeremiah** [comment]
I can confirm this. I experienced it in the Rustic Waters II modpack (so it has existed in older versions of TSS). Putting the SD controller in a position where it doesn't connect to the network (which doesn't seem to work throuhg SD trim) was the only workaround I found.

**Comment by ffuentesm** [comment]
Yep, apparently it counts the items from the storage controller, then again the items in the drawers, the only way to fix this is the have the drawers or the controller touching the main network. Not both.

**Comment by ffuentesm** [comment]
Closed: Intended design.
