### ISSUE TITLE
Can't move recipes into table from EMI

### ISSUE THREAD

**Issue by ryleu** [tom5454/Toms-Storage#186]
I'm unable to move EMI recipes into the crafting terminal. According to the developer of EMI, it is up to the individual mod developers to implement. I'd love to see this mod work with EMI because of how much more powerful it is when compared to REI.

**Comment by broadcast** [comment]
+1 I also tested this with JEI and it looks like it doesn't support moving recipes into the crafting terminal as well.

**Comment by tom5454** [comment]
Should work in the latest release
