### ISSUE TITLE
[Suggestion] remove infinite range

### ISSUE THREAD

**Issue by CrusaderRabbit** [tom5454/Toms-Storage#194]
Can we please have a config that disables the infinite range of beacons? I don't mind having it be an exponential range but having your entire base wherever you are is pretty op.

Minecraft version: 1.18.2
Forge

**Comment by exavian** [comment]
I feel the same. I like the mod, but infinite range across all dimensions is way too strong for my tastes. There doesn't seem to be a way to turn off the feature that I can tell. Setting the config to invalid beacon levels causes the values to reset to the default.
