### ISSUE TITLE
Terminals not working after 1.19.2 - 1.5.0 Update

### ISSUE THREAD

**Issue by DenEgg** [tom5454/Toms-Storage#195]
Just upgraded on 1.19.2 from 1.3.10 to 1.5.0 and Mod loads as always, but when accessing the Terminals they're not detecting my Chests. Can't see my Items and can't deposit them. The Inventory Connector detects the Chests (128x Obsidian Chest from Iron Chests, 13.824 Slots total). As said, in 1.3.10 the Terminals worked wonderful and detected all Chests.

For now I'm staying on 1.3.10, because I had no Issues on this Version.

**Comment by tom5454** [comment]
Please post your minecraft log

**Comment by DenEgg** [comment]
[2023-02-14-1.log](https://github.com/tom5454/Toms-Storage/files/10735984/2023-02-14-1.log)

**Comment by tom5454** [comment]
Can you send a screenshot of your setup? I couldn't reproduce the issue.
