### ISSUE TITLE
JEI Auto place crafting (the + button)

### ISSUE THREAD

**Issue by sargeow** [tom5454/Toms-Storage#198]
The plus (+) in JEI doesnt display when in the crafting terminal unlike AE2 or enderIO if you remember that relic.
Quilt client/server 1.19.2 (newest)
1.19-1.4.6
![Screenshot_1](https://user-images.githubusercontent.com/89289084/220006810-65322ab8-c099-48fb-8ca9-187b141fadec.png)

**Comment by tom5454** [comment]
Update the mod, JEI on fabric/quilt was not supported in that version.

**Comment by sargeow** [comment]
Ah thank you!
