### ISSUE TITLE
Only items from one inventory shows up if they are connected with cables

### ISSUE THREAD

**Issue by DedMaxim** [tom5454/Toms-Storage#2]
Simple system like this but only items from one chest can be accessed for some reason:
![image](https://user-images.githubusercontent.com/41780875/86759662-7f1c9c00-c066-11ea-9d6c-2f9b4ef2ae1b.png)

**Comment by tom5454** [comment]
In the 1.15 version
the inventory cables are designed for long range one to one connections. Use the Inventory Connector and Inventory Trims to connect them like this.

Check out the 1.16 version where I changed the Inventory Cable, to work similarly to this.
