### ISSUE TITLE
Fabric [1.4.6](1.19.2) Inventory Cable Connector (Filtered) stops filtering items

### ISSUE THREAD

**Issue by dre3002** [tom5454/Toms-Storage#201]
Inventory Cable Connector (Filtered) stops filtering items after a certain point.

I have 10 Filters connected to 10 chests and (see linked picture) and a Inventory Cable Connector that is attached to a dropper.

This is a mob grinder. Items flow from the hoppers above into chests. 4 Basic Inventory Hoppers pass the items to a Inventory Connector which then passes the items through the filters, and then the dropper at the end. The filters are set to capture the drops I want. Everything else gets dispensed by the dropper into lava.

This system worked perfectly fine at first but then at some point (I believe it was maybe when I left the area (unloaded chunks) and came back) it broke and some of the filters no longer capture the items and they get dispensed in lava. I have tried breaking and replacing all the filters and connectors but it wont work as expected anymore. 

[Screenshot of setup](https://prnt.sc/n-_v_rz-mQJZ)

Wondering if I am doing something wrong or if this is a bug.

**Comment by tom5454** [comment]
Update the mod, and use the new priority setting on filtered inventory cable connectors. In older versions the insert order was random.
