### ISSUE TITLE
Crash when right clicking on Inventory Cable (Filtered)

### ISSUE THREAD

**Issue by cattywhompus** [tom5454/Toms-Storage#203]

**Comment by IcedCoffeee** [comment]
Also experiencing this, playing on [Dreamcraft FABRIC](https://www.curseforge.com/minecraft/modpacks/dreamcraft-new)
 - [latest.log](https://gist.github.com/IcedCoffeee/7007a5cd159d282dbf65b7f5f98ccd38)
 - [crash report](https://gist.github.com/IcedCoffeee/a46eca40d166b7446ce38eb835342487)

**Comment by jmtayamada** [comment]
Crashes most of the time for me, though I managed to open the filtered inventory connector once

**Comment by devinquast** [comment]
what was the solution? I'm having the exact same issue.

**Comment by jmtayamada** [comment]
> what was the solution? I'm having the exact same issue.

It should've been fixed in the current update
