### ISSUE TITLE
[1.18.2 FORGE] Right Click on terminal item does not pick half of the items

### ISSUE THREAD

**Issue by ffuentesm** [tom5454/Toms-Storage#208]
Tom's Simple Storage Mod: 1.4.0

So, when you right-click on pick an item, you should pick half of the things up to half a stack. 
But for some reason, when I right-click to pick up items from the inventory, I always pick 32 items, or all the things if they are less than 32. 

![image](https://user-images.githubusercontent.com/44974827/222818479-d8b41400-a46b-4690-b97d-d503416675a3.png) 
![image](https://user-images.githubusercontent.com/44974827/222818591-9596a8ac-ee60-405a-b642-d0717bda5a59.png)

Also, when I shift Right click on an item to quickly add it to my inventory, After the transfer, the item stays displayed on the terminal UI with a number count of 0 until I stop pressing SHIFT. So I can no longer quickly clean up the terminal. 

You can see here ono the Iron sheets
![image](https://user-images.githubusercontent.com/44974827/222820362-fef47116-93de-4003-9360-92fd1b3eaea4.png)

**Comment by jmadarg** [comment]
I think the first thing is controlled via one of the settings on the left, the one that you can select Vanilla Controls and such.
The second thing is (as far as I know) a feature to avoid accidentally pulling items you don't want when shift-right clicking (see https://github.com/tom5454/Toms-Storage/issues/155#issue-1396480560 )

**Comment by ffuentesm** [comment]
I am selected to be Vanilla behaviour, so I find it weird that I am getting 32 items instead of half the items. 
Is there a way to "turn off" the "Shift+Right click safety" mode?

**Comment by jmadarg** [comment]
Have you tried the other modes?
Idk if it can be turned off, I still haven't used the latests versions, because I play on a server.
