### ISSUE TITLE
Using Recipe Book from Crafting Terminal Issue

### ISSUE THREAD

**Issue by Sultansmooth** [tom5454/Toms-Storage#210]
when using the recipe book, anything in the crafting terminal shows as red. Used to automatically pull it and put the items in the crafting menu.

**Comment by Sultansmooth** [comment]
![image](https://user-images.githubusercontent.com/12436876/222974832-5a1df44d-0da8-4a70-b7c7-0f97822426ac.png)

**Comment by Sultansmooth** [comment]
anyone else experiencing this bug?

**Comment by TheRisingUnited** [comment]
> anyone else experiencing this bug?

same problem here
