### ISSUE TITLE
[Question] Hopper interaction with redstone

### ISSUE THREAD

**Issue by jmadarg** [tom5454/Toms-Storage#212]
Not really an issue, but didn't found Amy other place where to ask this.
Hopper locking is a very important step in redstone-based automation, specially in heavily modded smps, but these modded hoppers seem to interact with redstone in a very different way than vanilla hoppers, because the only way I've found to reliably lock them is to use a lever right next to them.
So I wanted to know if this limited redstone interaction is intended and if there is any other way to lock them in a more automated way.
Ideally having the same behavior as vanilla hoppers would be awesome, but is understandable if that is not planned or even possible.

**Comment by tom5454** [comment]
The code is exactly the same as the vanilla hopper, and it works the same in my dev enviroment. Can you send me your mod list and a screenshot of a redstone setup that doesn't work?

**Comment by jmadarg** [comment]
Oh, thats interesting. I play mainly using the [MMC1 - Fabric modpack](https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric), and I think the only mod that changes redstone behavior should be [Alternate Current](https://www.curseforge.com/minecraft/mc-mods/alternate-current).
Gonna do some more testing and see what happens.

**Comment by jmadarg** [comment]
Ok, nvm, must have been a temporary incompat or maybe a problem on previous versions (MMC got updated just recently).
Thanks for your time!
