### ISSUE TITLE
[Suggestion] More rows on Terminal UI 

### ISSUE THREAD

**Issue by Shadowrs** [tom5454/Toms-Storage#215]
Default chest is 3x9
Double chest 6x9
Backpacks (sophisticated backpacks mod) - anywhere from 3x9 to 9x9 and probably bigger

Can this be made adjustable adjustable via an option in the server config? 

On larger screens, viewing is a much more plesent experience when I can see more items. I'm hoping the scroll bar won't break and it will just magically work. 

![](https://i.imgur.com/g1MUHhL.png)
![](https://i.imgur.com/xjcku4F.png)

**Comment by Telezhka-the-First** [comment]
FINALLY
This mod is ideal now! Thank you!

**Comment by Shadowrs** [comment]
Massive thanks ! ![](https://i.imgur.com/SFI8WOb.png)
