### ISSUE TITLE
Priority Error 1.19.2

### ISSUE THREAD

**Issue by redspecsgaming** [tom5454/Toms-Storage#219]
So i have my items setup to filter to specific storage areas using filtered inventory cable connectors. I have several of these connected to inventory connectors which then connect to a large block of barrels. This is so I can filter similar items types to specific areas. I have several areas setup like this (wood area, stone area, building parts area, ect) and then I have one final area for everything else not specified. This area uses a single non filtered inventory cable connector connected to an inventory connector. This system works pretty well to keep my items sorted out.

The bug occurs when I quit the game and come back later. What happens then is items I have specifically filtered for in another area will often times end up in the "catch all" area instead. I have found I can fix this by breaking the non filtered inventory cable connector on the catch all area and putting it back, which then fixes the priority of item sorting for that game session. However I find I am having to do that each time I start playing.

**Comment by tom5454** [comment]
Please post your minecraft log

**Comment by redspecsgaming** [comment]
Sure no problem. I rebooted my server and ran a test after logging in and a stack of Ebony Logs that have a filter elsewhere ended up in the "catch all" area. I am attaching both the server and client logs here. I also found a video where he shows/describes exactly what I am seeing if this makes more sense: https://www.youtube.com/watch?v=U68JLSmSObg
[Server.log](https://github.com/tom5454/Toms-Storage/files/11034065/Server.log)
[Client.log](https://github.com/tom5454/Toms-Storage/files/11034066/Client.log)

**Comment by tom5454** [comment]
Update the mod, and use the new priority setting on filtered inventory cable connectors. In older versions the insert order was random.
