### ISSUE TITLE
Advancement not granted when using the crafting terminal

### ISSUE THREAD

**Issue by 630R63** [tom5454/Toms-Storage#235]
Hello!

Currently playing the Better Minecraft [FABRIC] modpack for 1.19.2.
The modpack is using the fabric version 1.5.4 of this mod.
Been trying to get an advancement from the mod The Bumblezone in which you have to craft 24 beehives or bee nests.

Crafting them using the Crafting Terminal, didn't grant the advancement:
![image](https://user-images.githubusercontent.com/6078866/235633981-44c6de35-9723-4596-ba3b-416dbffa2713.png)
![image](https://user-images.githubusercontent.com/6078866/235634051-775950cf-2ce1-4982-9d19-31d5cebd02ac.png)
![image](https://user-images.githubusercontent.com/6078866/235633484-413c629b-207c-4847-8389-046fe71a8fa7.png)

When using the crafting table to craft the beehives, I did get the advancement:
![image](https://user-images.githubusercontent.com/6078866/235634179-cb509afc-fe9c-4ac0-930c-00f67a60a218.png)

The Bumblezone mod author was thinking that this should work for any crafting method or recipe that has a Beehive or Bee Nest as result. Only way it won't work is if you're using some sort of custom crafting system that is not using a ResultSlot or they forgot to fire checkTakeAchievements method upon taking items out of their custom system's ResultSlot.

So since the interface has a ResultSlot, maybe the advancement check is not triggered? Could you please check?

Thank you!

**Comment by TelepathicGrunt** [comment]
This is the method that the Crafting Terminal's result slot should be firing when a players crafts and removes the result item from the ResultSlot to properly grant advancements and update item craft stat too. If not using the vanilla ResultSlot here, maybe extend that slot to implement the behaviors you want while underlying checkTakeAchievements still runs for best mod compat when they may be hooked into that method
![image](https://user-images.githubusercontent.com/40846040/235652695-3f7b482c-ad4f-4556-b9e6-d373eef3c659.png)
