### ISSUE TITLE
Change the Curio slot for Adv. Wireless Terminal from "Belt" to something like "Pocket" or "Wrist"

### ISSUE THREAD

**Issue by Telezhka-the-First** [tom5454/Toms-Storage#236]
Adv. Wireless Terminal seems to be a hand-held or wrist item, like watches, so it would better fit a slot like "Pocket" or "Wrist". This would also free up an overencumbered "Belt" slot for other items.

**Comment by ffuentesm** [comment]
I think that just naming it curio slot allows it to be placed in any slot type.
