### ISSUE TITLE
[1.16.4] [FABRIC] Feature request

### ISSUE THREAD

**Issue by kwpugh** [tom5454/Toms-Storage#24]
Hi,

We are loving this mod on our Fabric server, great work!!

Would it be possible to add to the crafting terminal a display of empty slots in the system.   This would be a great addition to help better manage capacity.  When the attached slots run out of free slots, there is no indication in the GUI that you are out of space, you just can't add more to the system.

Thank you for considering.

Regards.

**Comment by tom5454** [comment]
Added: You can right click the inventory connector to see the remaining empty slots in your storage system.
