### ISSUE TITLE
Infinite range

### ISSUE THREAD

**Issue by taz444** [tom5454/Toms-Storage#240]
I have the lvl 4 beacon but i cant seem to get my advance wireless terminal to have infinite range and idk how to fix it. I've tried two different beacons and a new storage setup but the infinite range still wont work for me.

**Comment by MrEndermen** [comment]
I was able to resolve the issue with my storage system, as i was having this problem as well.
#1 The chunk that has the crafting/storage terminal you are using must be loaded.
#2 The CHESTS that have your items that have a cable connected to your crafting terminal seem to need to be loaded as well.

I have a map mod and if I open my map and right click and claim the chunk that my beacon is on, that has the crafting terninal next to it, i was not able to access the crafting terminal from an extreme distance or in the Nether.

After I claimed and forceloaded the chunk that contains my storage chests I was able to use the advanced crafting terminal. I don't know if that was the fix or if I just happened to do something else that resolved it but I thought this might help.
