### ISSUE TITLE
Two different Inventory Trim blocks

### ISSUE THREAD

**Issue by mrukas** [tom5454/Toms-Storage#244]
The mod adds two different inventory trim blocks. One of them is displayed correctly, the other one makes the ground invisble.
Im not sure why this is happening. I created a new instance of minecraft with only this mod and the fabric api active. 

![2023-05-22_18 51 26](https://github.com/tom5454/Toms-Storage/assets/12882255/7bc24bbc-15bc-43f3-8bf5-39b824127fe5)
![2023-05-22_18 52 42](https://github.com/tom5454/Toms-Storage/assets/12882255/79b70d45-d686-493a-9152-21d6a134b154)

**Comment by tom5454** [comment]
The invisible one is the painted variant. It *shouldn't* show in the creative inventory
