### ISSUE TITLE
Flywheel breaks infinite terminal range

### ISSUE THREAD

**Issue by ManMadeDracon** [tom5454/Toms-Storage#245]
I found that having the mod flywheel running at the same time seems to cause the extended terminal distance from a beacon to not work. I assume this has something to do with the components being rendered differently, but I know very little about this sort of issue.

Mod Version: 1.2.19
Game Version: 1.16.5

**Comment by tom5454** [comment]
1.16.5 doesn't have that feature, it's 1.18+ exclusive
