### ISSUE TITLE
Crash When Right Click Filtered Connector

### ISSUE THREAD

**Issue by JLL612310** [tom5454/Toms-Storage#249]
---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-06-04 07:32:39
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "com.tom.storagemod.util.Priority.ordinal()" because "this.field_2797.priority" is null
	at com.tom.storagemod.gui.InventoryConnectorFilterScreen.method_25394(InventoryConnectorFilterScreen.java:47)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.tom.storagemod.gui.InventoryConnectorFilterScreen.method_25394(InventoryConnectorFilterScreen.java:47)

-- Screen render details --
Details:
	Screen name: com.tom.storagemod.gui.InventoryConnectorFilterScreen
	Mouse location: Scaled: (480, 246). Absolute: (960.000000, 492.000000)
	Screen size: Scaled: (960, 492). Absolute: (1920, 984). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['JL_Lbee'/54410, l='ClientLevel', x=930.65, y=88.00, z=1920.50]]
	Chunk stats: 461, 461
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,64,-32), Section: (at 0,0,0 in -3,4,-2; chunk contains blocks -48,-64,-32 to -33,319,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 9483537 game time, 11430187 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Supplementaries Generated Pack, Create Legacy Copper, Darker Ropes, KubeJS Resource Pack [assets]

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.5, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1188762352 bytes (1133 MiB) / 4026531840 bytes (3840 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i9-12900K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2208
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2849
	Graphics card #1 name: Intel(R) UHD Graphics 770
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x4680
	Graphics card #1 versionInfo: DriverVersion=31.0.101.3616
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 36782.81
	Virtual memory used (MB): 28580.43
	Swap memory total (MB): 4234.79
	Swap memory used (MB): 139.87
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		accelerateddecay: Accelerated Decay 1.0.0+mc1.19.2
		advancednetherite: Advanced Netherite 1.6.6-1.19.2
		adventurez: AdventureZ 1.4.17
		ae2: Applied Energistics 2 12.9.2
			noindium: No Indium? 1.1.0+1.19
		ambientsounds: Ambient Sounds (Fabric) 5.2.13
		antiblocksrechiseled: AntiBlocksReChiseled 0.1.9
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.5.69
		balm-fabric: Balm 4.5.2+0
		bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
		bclib: BCLib 2.1.6
		bestylewither: BE Style Wither 1.3.2
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.1
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		bookshelf: Bookshelf 16.2.17
		bwncr: Bad Wither No Cookie Reloaded 3.14.1
		campanion: Campanion 4.1.2+fabric
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		chunky: Chunky 1.3.38
		cleancut: CleanCut 1.19.2-5.1-fabric
		clickmachine: Kenza's Click Machine 1.3.0
			fake-player-api: Fake Player API 0.4.0
			kirin: Kirin UI 1.11.0
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+14
		colorfulazaleas: Colorful Azaleas 2.2.0
		consistency_plus: Consistency Plus 0.5.1+1.19.2
			stonecutter_recipe_tags: Stonecutter Recipe Tags 4.0.0+1.19.9b8d04c.fabric
		controlling: Controlling For Fabric 10.0+7
		cookingforblockheads: Cooking for Blockheads 13.3.0
		cottonly: Cottonly 0.12.1
		coxinhautilities: Coxinha Utilities 1.4.5+1.19
			yet-another-config-lib: YetAnotherConfigLib 1.6.0
		craftingtweaks: Crafting Tweaks 15.1.0
		create: Create 0.5.0.i-961+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.8.a-4
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.1.784+1.19.2
				com_github_llamalad7_mixinextras: MixinExtras 0.1.1
				forge_tags: Porting Lib Tags 3.0
				mm: Manningham Mills 2.3
				porting_lib_accessors: Porting Lib Accessors 2.1.784+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.784+1.19.2
				porting_lib_base: Porting Lib Base 2.1.784+1.19.2
				porting_lib_common: Porting Lib Common 2.1.784+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.784+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.784+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.784+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.784+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.784+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.784+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.784+1.19.2
				porting_lib_models: Porting Lib Models 2.1.784+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.784+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.784+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.784+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.50-MC1.19.2
		creativecore: CreativeCore (Fabric) 2.9.3
		creaturesfromthesnow: Creatures from The Snow 4.1.0+1.19.2
		darkutils: DarkUtilities 13.1.7
		decorative_blocks: Decorative Blocks 3.0.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		dragonfight: Dragonfight Mod 1.19.2-2.7
		echoingdepths: Echoing Descent 1.0.0-1.19.2
		effective: Effective 1.4
		effectivelogremover: Effective Log Remover 1.0.0
		enchdesc: EnchantmentDescriptions 13.0.14
		enderchests: EnderChests 1.1.1
		endrem: End Remastered 5.2.0
		entityculling: EntityCulling-Fabric 1.6.1-mc1.19.2
		explorerscompass: Explorer's Compass 1.19.2-2.2.0-fabric
		fabric-api: Fabric API 0.73.2+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.24+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.7+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.35+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.5+dce4603e90
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.38+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.12+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.15+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.23+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.1+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.1+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricenchantments: Fabric Enchantments 0.9.0
		fabricloader: Fabric Loader 0.14.12
		fancymenu: FancyMenu 2.13.3
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		farsight: Farsight Mod 1.19-2.4
			com_github_jctools_jctools_jctools-core: jctools-core v4.0.1
		fastload: Fast Load 2.6.11
		forgeconfigapiport: Forge Config API Port 4.2.11
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		ftbauxilium: FTB Auxilium 1900.1.8-build.39
		ftbbackups2: FTB Backups 2 1.0.18
		ftbchunks: FTB Chunks 1902.3.15-build.233
		ftblibrary: FTB Library 1902.3.14-build.184
		ftbpc: FTB Pack Companion 2.0.3-build.8+mc1.19.2
		ftbquests: FTB Quests 1902.4.9-build.195
		ftbteams: FTB Teams 1902.2.12-build.95
		ftbultimine: FTB Ultimine 1902.3.5-build.65
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		handcrafted: Handcrafted 2.0.2
		healthoverlay: Health Overlay 7.2.4
			fiber: fiber 0.23.0-2
		hugestructureblocks: Huge Structure Blocks 1.0.6
		indium: Indium 1.0.9+mc1.19.2
		indrev: Industrial Revolution 1.15.1-BETA
			magna: Magna 0.5.2-1.19.1
				omega-config: OmegaConfig 1.0.8
			patchouli: Patchouli 1.19-74-FABRIC
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		ingredient-extension-api: Ingredient Extension API 3.0.6
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemfilters: Item Filters 1902.2.9-build.46
		jade: Jade 8.7.3
		jamlib: JamLib 0.6.0+1.19
		java: OpenJDK 64-Bit Server VM 17
		kibe: Kibe 1.9.11-BETA+1.19
			playerabilitylib: Pal 1.6.0
		konkrete: Konkrete 1.6.0
		kubejs: KubeJS 1902.6.0-build.142
		lazydfu: LazyDFU 0.1.3
		lightoverlay: Light Overlay 7.0.0
		lithium: Lithium 0.10.4
		lootjs: LootJS 2.7.9
		lootr: Lootr 0.4.25.64
		merequester: ME Requester 1.19.2-1.0.3
		midnightlib: MidnightLib 1.0.0
		minecraft: Minecraft 1.19.2
		minetogether: MineTogether 6.0.15
		modmenu: Mod Menu 4.2.0-beta.2
		moonlight: Moonlight 1.19.2-2.2.10
		morebows: More Bows Restrung 1.0.8+1.19.x
		morejs: MoreJS 0.0.7
		mousetweaks: Mouse Tweaks 2.22
		mousewheelie: Mouse Wheelie 1.10.7+mc1.19.2
			amecsapi: Amecs API 1.3.7+mc22w17a
			coat: Coat 1.0.0-beta.19+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.7.1+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.3+mc22w17a
		naturescompass: Nature's Compass 1.19.2-2.1.0-fabric
		nbtcrafting: NBT Crafting 2.2.3+mc1.19
		netherportalfix: NetherPortalFix 10.0.1
		openblocks: Open Block Elevator Mod 0.0.2-1.19.X
		owo: oωo 0.9.3+1.19
			blue_endless_jankson: jankson 1.2.1
		pigpen: PigPen 11.1.2
		pling: Pling 1.5.0
		polylib: PolyLib 1900.0.2-build.42
		polymorph: Polymorph 0.46.1+1.19.2
			spectrelib: SpectreLib 0.11.0+1.19
		ponderjs: PonderJS 1.1.10
		powah: Powah! 4.0.6
		puzzleslib: Puzzles Lib 4.3.12
		reborncore: Reborn Core 5.4.0
			team_reborn_energy: Energy 2.3.0
		reinfbarrel: Reinforced Barrels 2.3.0+1.19
			reinfcore: Reinforced Core 3.0.3+1.19
		reinfchest: Reinforced Chests 2.2.0+1.19
		rhino: Rhino 1902.2.2-build.264
		rightclickharvest: Right Click Harvest 3.1.0+1.19-1.19.2
		roughly_enough_loot_tables: Roughly Enough Loot Tables 1.19-1.0
		roughly_enough_trades: Roughly Enough Trades 1.19-1.0
		roughlyenoughitems: Roughly Enough Items 9.1.591
			error_notifier: Error Notifier 1.0.9
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		runelic: Runelic 14.1.4
		satin: Satin 1.9.0
		sdrp: Simple Discord Rich Presence 3.0.4-build.27+mc1.19.2
		shetiphiancore: ShetiPhianCore 1.3.4
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		skyvillages: Sky Villages 1.0.2.1
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		spark: spark 1.10.29
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		spiceoffabric: Spice of Fabric 1.6.0-beta.2+1.19.2
		spirit: Spirit 2.2.3
			resourcefullib: Resourceful Lib 1.1.12
		strawstatues: Straw Statues 4.0.10
		summoningrituals: Summoning Rituals 1.19.2-2.0.4
		supplementaries: Supplementaries 1.19.2-2.2.50
		tia: Tiny Item Animations 1.19.2-1.0.0
		tipsmod: Tips 8.0.27
		tipthescales: Tip The Scales 6.0.10
		tlc: The Lost Castle 1.0.0
		toms_storage: Tom's Simple Storage Mod 1.5.0
		tooltipfix: ToolTip Fix 1.1.1-1.19
		trade_cycling: Trade Cycling 1.19.2-1.0.5
		trashcans: Trash Cans Mod 0.0.2-1.19.X
		trashslot: TrashSlot 12.0.1
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.13
		travelerstitles: Traveler's Titles 1.19.2-Fabric-3.1.0
		trinkets: Trinkets 3.4.2
		visuality: Visuality 0.5.5
		visualworkbench: Visual Workbench 4.2.2
		voidz: VoidZ 1.0.9
		waystones: Waystones 11.1.0
		xlpackets: XLPackets 1.19.2-4
		xp_storage: XP Storage 1.4.3+1.19
		xp_storage_trinkets: XP Storage - Trinkets 0.1+1.19
		xps: Xp Obelisk 0.4.7-r+1.19.2-Fabric
		yigd: You're in Grave Danger 1.4.8
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.7
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-1.19.2-0.14.12
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.49, NVIDIA Corporation
	Window size: 1920x984
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, Supplementaries Generated Pack, Create Legacy Copper, Darker Ropes
	Current Language: English (US)
	CPU: 24x 12th Gen Intel(R) Core(TM) i9-12900K

**Comment by tom5454** [comment]
Update the mod, you are using `1.5.0` the current latest is `1.5.7`.
