### ISSUE TITLE
Can't get it to work in 1.15.2

### ISSUE THREAD

**Issue by alfuken** [tom5454/Toms-Storage#25]
Minecraft 1.15.2
Forge 31.2.47
toms_storage-1.1.5.jar

MC with only forge and this mod installed, no config altered. Made a bunch of chests, loaded with stuff, attached a terminal, and it shows only contents of a chest directly behind it. Doesn't show the content of adjacent chests.

Basically, a serie of screenshots says it all: https://imgur.com/a/1A0KOtp

What's wrong?..

**Comment by tom5454** [comment]
You need an Inventory Connector behind the terminal. The terminal can only see the inventory it's placed on. The Inventory Connector combines the inventories into one.

**Comment by alfuken** [comment]
Hm. That's quite not obvious... why wouldn't you combine the functionality of Inventory Connector with Terminal?
