### ISSUE TITLE
Crash upon opening Terminal or Crafting Terminal - 1.20.1

### ISSUE THREAD

**Issue by xKiilash** [tom5454/Toms-Storage#253]
Shows the screen briefly before the game force closes.

[Log](https://paste.ee/p/yKMWX)

Here's the log, hope this helps.

**Comment by tom5454** [comment]
It's Visual Overhaul and World Host breaking each other. I don't see any mention to tom's simple storage in the crash log. You opened the Mods Screen.

**Comment by xKiilash** [comment]
Sorry, wrong one, this is the latest one:

-- Affected screen --
Details:
	Screen name: com.tom.storagemod.gui.CraftingTerminalScreen
	
https://paste.ee/p/vb7vO

**Comment by tom5454** [comment]
One of your mods breaks the recipe book, Apparently it's `Visualoverhaul` (#251), but I can't see why.

**Comment by ProsperCraft** [comment]
I think my crash may be related, not sure-  java.lang.NullPointerException: Cannot invoke "net.minecraft.world.inventory.Slot.m_6657_()" because "containerScreen.f_97734_" is null

https://gist.github.com/ProsperCraft/3b9e8bf853433729d477f19a1598d7be

Modpack- TownCraft for 1.20.1

**Comment by tom5454** [comment]
> I think my crash may be related, not sure- java.lang.NullPointerException: Cannot invoke "net.minecraft.world.inventory.Slot.m_6657_()" because "containerScreen.f_97734_" is null
> 
> https://gist.github.com/ProsperCraft/3b9e8bf853433729d477f19a1598d7be
> 
> Modpack- TownCraft for 1.20.1

The issue is with Equipment Compare
https://github.com/AHilyard/EquipmentCompare/issues/28

**Comment by AHilyard** [comment]
Sorry for the inconvenience everyone.  I've just released updates to Equipment Compare that fixes this crash.
