### ISSUE TITLE
Hopper does not pull blocks from chests

### ISSUE THREAD

**Issue by JorjGaidin** [tom5454/Toms-Storage#260]
I have tried every way I can think of it but I can not get the inventory hopper to pull items from my chest. I've tried with and without filters and all other combinations. I'm wondering if there's a compatibility issue with another mod I have installed?

light-overlay-8.0.0.jar
terrestria-6.0.7.jar
toms_storage_fabric-1.20-1.6.2.jar
supermartijn642corelib-1.1.10-fabric-mc1.20.jar
shulkerboxtooltip-fabric-4.0.3+1.20.jar
Gamma-Utils-1.7.15-mc1.20.1.jar
clutter-1.20-0.3.7.jar
cinderscapes-4.0.6.jar
XaerosWorldMap_1.30.6_Fabric_1.20.jar
traverse-7.0.7.jar
jei-1.20-fabric-14.0.0.11.jar
betterarcheology-1.0.2.jar
quickpaths-1.20.0-3.0.jar
journeymap-1.20-5.9.8-fabric.jar
AdditionalStructures-1.20.x-(v.4.2.0).jar
DiagonalFences-v7.0.0-1.20-Fabric.jar
visible-barriers-2.0.4.jar
PuzzlesLib-v7.0.9-1.20-Fabric.jar
Mo-Glass-1.6.1-MC1.20.1.jar
TaxFreeLevels-1.3.3-fabric-1.19.jar
grind-enchantments-3.1.2+1.20.jar
enchantments-plus-fabric-1.1.7+1.20.jar
fastback-0.11.0+1.20.0.jar
mob-captains-v2.1.2.jar
mine-spawners-1.0.jar
recast-1.20.0-3.0.jar
librarian-trade-finder-2.0.1.jar
spellbound-weapons-v4.0.5f.jar
WorldEdit-CUI-Mod-Fabric-1.20.jar
libIPN-fabric-1.20-3.0.2.jar
fabric-language-kotlin-1.9.4+kotlin.1.8.21(1).jar
modmenu-7.0.1.jar
expandedstorage-10.0.0-beta.3+1.20-fabric.jar
immersive-portals-3.0.2-mc1.20-fabric.jar
continuity-3.0.0-beta.2+1.20.jar
carpet-tis-addition-mc1.20.1-v1.48.1.jar
Xaeros_Minimap_23.5.0_Fabric_1.20.jar
SimpleCopperPipes-1.13.3.jar
Jade-1.20-fabric-11.1.2.jar
c2me-fabric-mc1.20-0.2.0+alpha.10.88.jar
Clumps-fabric-1.20-11.0.0.1.jar
architectury-9.0.8-fabric.jar
WilderWild-2.0.4-Fabric+1.20.jar
repurposed_structures-7.0.0+1.20-fabric.jar
voxelmap-1.20-1.12.8.jar
ForgeConfigAPIPort-v7.0.0-1.20-Fabric.jar
worldedit-mod-7.2.15.jar
autotools-1.5-fabric-1.20.1.jar
geckolib-fabric-1.20-4.2.jar
guiclock-1.20.0-4.2.jar
T6-AutoAttack_Fabric-1.20.jar
NoDoubleSlabPlacement-1.0.0+1.20.jar
reacharound+1.20-1.1.2.jar
bottleyourxp-1.20.0-3.1.jar
nmuk-1.1.0+mc1.20-pre2.jar
mousewheelie-1.11.1+mc1.20-pre2.jar
cloth-config-11.0.99-fabric.jar
midnightlib-fabric-1.4.0.jar
enchantmentcompat-1.2.1+1.20.jar
amethyst-cutting-1.0.jar
experiencebottler-1.20+build.1.jar
trashcans-1.0.17-fabric-mc1.20.jar
supermartijn642configlib-1.1.6-fabric-mc1.20.jar
chunkloaders-1.2.3-fabric-mc1.20.jar
ferritecore-6.0.0-fabric.jar
DurabilityNotifier-fabric-1.20-1.6.0.jar
collective-1.20.0-6.57.jar
doubledoors-1.20.0-4.5.jar
compose-1.3.0.jar
cooldown-coordinator-0.6.1.jar
ductwork-0.7.3.jar
Pick-Block-Pro-1.7.19-mc1.20.jar
indium-1.0.18+mc1.20.jar
fabric-carpet-1.20-1.4.112+v230608.jar
iris-mc1.20-1.6.4.jar
FallingTree-1.20-4.0.0.jar
sodium-fabric-mc1.20-0.4.10+build.27.jar
fabric-api-0.83.0+1.20.jar

**Comment by tom5454** [comment]
Please send a screenshot of your setup

**Comment by JorjGaidin** [comment]
Found the problem. I needed to have the hopper go into an inventory connector before it passes to the chests.
