### ISSUE TITLE
Feature Request - Inventory Hoppers

### ISSUE THREAD

**Issue by corhean** [tom5454/Toms-Storage#271]
Inventory hoppers placed backwards against cables should extract from the system with the same ability for filter mechanics.  Much like putting a hopper below a barrel can pull out, would enjoy to pull things out of existing storage. Or allow the open crate to push into inventories attached (like say a shulker box).

**Comment by tom5454** [comment]
The Inventory Hopper should work both ways, but you have to set a filter to extract from the network.

**Comment by corhean** [comment]
ah. you're right. For some reason we weren't doing the right combo.
