### ISSUE TITLE
Crash when clicking on an item

### ISSUE THREAD

**Issue by SattesKrokodil** [tom5454/Toms-Storage#28]
https://pastebin.com/6rBBGCyV

**Comment by tom5454** [comment]
You clicked on an item that has a null in it's tag, normally this is not posible. One of your mods puts a null into the item tag.
This is an issue with one of your other mods.

**Comment by goldern** [comment]
@tom5454 shouldn't your mod ignore null tags?

**Comment by tom5454** [comment]
The null tag is deeply within the item tag. Attempting to write this item with vanilla code will crash.
