### ISSUE TITLE
TOMS crafting terminal  not compatible to  EMI recipes

### ISSUE THREAD

**Issue by SirBastol** [tom5454/Toms-Storage#289]
the synced rei /jei  option does not sync nor search EMI 
  emi is a better system  and  cleaner..  
  simpler.. 
  but just s powerful

**Comment by tom5454** [comment]
What's your minecraft version, Tom's Simple Storage version, and EMI version? Are you using Forge or Fabric?

**Comment by SirBastol** [comment]
https://modrinth.com/modpack/hermitcreateflavors

That’s the build currently
It does the same I. Fabric and forge. 1.19 and 1.20

Currently forge 1.20.1.  Latest x.2.0 release forge server

**Comment by darkralts** [comment]
the recipes still not working

<img width="606" height="246" alt="Image" src="https://github.com/user-attachments/assets/43d48c6d-de9c-4b7f-9747-b15e2d1fe69d" />

**Comment by darkralts** [comment]
1.21.1 on fabric emi clicking it shows nothing i have no idea how to craft anything
