### ISSUE TITLE
Loop detected when there is no loop

### ISSUE THREAD

**Issue by DedMaxim** [tom5454/Toms-Storage#3]
Setup like this gives an error that says "loop is detected", when it's clearly not the case. Also, items from only first chest are accessible
![image](https://user-images.githubusercontent.com/41780875/86760568-213c8400-c067-11ea-9e42-5e85d78f9a79.png)

**Comment by tom5454** [comment]
The inventory cables are designed for long range one to one connections. Use the Inventory Connector and Inventory Trims to connect them like this.
