### ISSUE TITLE
[Feature Request] Prioritize Outputs

### ISSUE THREAD

**Issue by Brand0n1** [tom5454/Toms-Storage#300]
What I want to be added is a menu added to the Inventory Connector, or a new block, that allows the player to set what block's inventory should be filled first. 

For example when used in conjunction with the Create and Extended Drawers mods with a setup like this (see image):
![image](https://github.com/tom5454/Toms-Storage/assets/35469559/079f0c48-edea-42ac-a7ba-c099d96395f2)

There should be an option to prioritize the drawers since they show the item count.

A block would probably be the best way to get this done since you can have a new block that goes in between 2 pipes and will make that pipe prioritized for items to be put into.

**_Edit:_**
Or just have it so that the chests that appear first in the pipeline would be filled first (see image below):
![image](https://github.com/tom5454/Toms-Storage/assets/35469559/9368928c-95e0-4730-9b3d-8f0cf439c571)

**Comment by tom5454** [comment]
Filtered cable connectors have a priority option, just leave the deny list empty.
