### ISSUE TITLE
Please Label Mod Correctly

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [tom5454/Toms-Storage#301]
https://dl.dropboxusercontent.com/scl/fi/tmeabolavh564z184bzo1/Discord_QuTRgDsbrv.png?rlkey=fiwmcaxq39vo7vtmjfjcm45hf&dl=0

``The NeoForged Project #announcements
SERVER
 — 11/13/2023 9:21 AM
Public Service Announcement 📣
CurseForge have notified us that a number of mods currently have releases for 1.20.2 that are marked both Forge and NeoForge which are causing issues for end users.

This is a good chance to remind modders that Forge and NeoForge are no longer compatible in 1.20.2.

Please remember to tag your 1.20.2 and newer files for the loaders the mod has been tested to work on.``

**Comment by tom5454** [comment]
It is labelled correctly, the latest release (1.6.7) is only for neoforge.
The normal Forge version is this one (1.6.6): https://legacy.curseforge.com/minecraft/mc-mods/toms-storage/files/4792110
