### ISSUE TITLE
the world is broken

### ISSUE THREAD

**Issue by psfdek** [tom5454/Toms-Storage#307]
![image](https://github.com/tom5454/Toms-Storage/assets/6521706/9ffa219e-8da1-4c10-9897-2b4ed236d31b) toms_storage:ts.inventory_cable_connector_filtered

This design breaks the world and prevents it from starting again.

toms_storage_fabric-1.19-1.4.5.jar
toms_storage_fabric-1.19-1.5.9.jar

**Comment by tom5454** [comment]
Please post your minecraft log

**Comment by psfdek** [comment]
hi
[crash-2023-12-03_23.16.47-server.txt](https://github.com/tom5454/Toms-Storage/files/13539815/crash-2023-12-03_23.16.47-server.txt)

https://github.com/tom5454/Toms-Storage/assets/6521706/89646d5f-fcce-4d1c-a418-09f831797bcb

**Comment by tom5454** [comment]
Try updating Fabric Api and Tom's Simple Storage
