### ISSUE TITLE
Priority Selection On Filtered Connector Missing

### ISSUE THREAD

**Issue by WhyKickAmooCow** [tom5454/Toms-Storage#314]
The priority selection on the filtered cable connector is absent on Tom's Storage 1.18.2-1.4.4.
https://github.com/tom5454/Toms-Storage/issues/205 https://github.com/tom5454/Toms-Storage/issues/300 https://github.com/tom5454/Toms-Storage/issues/291 and https://github.com/tom5454/Toms-Storage/issues/285 indicate that this should be an option.

![2024-01-11_02 29 05](https://github.com/tom5454/Toms-Storage/assets/13505247/b6685aa0-dc5c-4734-b0ec-03d23ad0ca77)

For this test, I am using the Forge 40.2.14 on Minecraft 1.18.2 with only Tom's Storage installed.

**Comment by tom5454** [comment]
That's a 1.19+ feature, it doesn't exist on 1.18.2.
