### ISSUE TITLE
Paint brush not working on fabric

### ISSUE THREAD

**Issue by AcediasGod** [tom5454/Toms-Storage#317]
Im using 0.15.6 fabric on minecraft 1.20.4, the paint kit paints every block as plain stone, im using a mod pack but no resource pack whatsoever.

**Comment by dfederspiel** [comment]
Possibly related to this: https://github.com/tom5454/Toms-Storage/issues/323

Indium was just updated for 1.20.4 and it fixed the "always stone" issue for me.
