### ISSUE TITLE
Item duplication when in storage system with Create Mod belts.

### ISSUE THREAD

**Issue by ryan-r-warner** [tom5454/Toms-Storage#324]
If a Create Mod belt is connected to an inventory system (at any point in the connection) it will pull items from the belt and convert them into the item you're trying to pull.

In the video, you can see the diamond on the belt be converted into emerald blocks when I try to pull the single emerald block out of the crafting terminal (and vice versa).

Version is 1.20.1, latest version of Tom's Simple Storage Mod (Fabric) in the BigChadGuysPlus modpack.

https://imgur.com/a/OWW1hE8

**Comment by SharperG7** [comment]
I'm also having this issue. a bunch of cobbled deepslate turned into unobtainium...

**Comment by SharperG7** [comment]
Perhaps a temporary solution would be adding a blacklist to the config? that way you could prevent certain "inventories" from being detected by the inventory connector, and thus making it so you can't pull stuff from the belts

**Comment by ryan-r-warner** [comment]
That would be a perfect solution, are you suggesting this to me as a fix
that is possible now or the dev to add? I can't tell haha
