### ISSUE TITLE
Advanced Wireless Terminal + Level 4 Beacon =/= Cross Dimensions

### ISSUE THREAD

**Issue by MuseOfWorlds** [tom5454/Toms-Storage#332]
I have a 6x Level 4 Beacon (244 blocks in a 10x11, 8x9,  6x7, 4x5, and then the Beacons on top in 2x3) with the Storage Terminal connected to the base. I CAN use it anywhere within the 'Same Dimension' (Overworld) but the 'All Dimensions' feature does not seem to work as I get 'Terminal Out of Range.

Edit: I am NOT able to pull up the inventory via the AWT within the same dimension, after all - outside of 64 blocks.

The chunks for the beacons and the terminal are force-loaded.
The Beacons
![image](https://github.com/tom5454/Toms-Storage/assets/163355234/26f77cc6-a18c-4e14-bfe8-6dddecb74dda)

The Map showing Force-Loaded Chunks and the active Buffs showing Level 4s
![image](https://github.com/tom5454/Toms-Storage/assets/163355234/3b1bea20-4db5-4461-915a-88adec0a2cb1)

The Terminal and connector at the bottom of the Beacons
![image](https://github.com/tom5454/Toms-Storage/assets/163355234/4a82cc37-8e76-4c62-b168-e27453e71161)
![image](https://github.com/tom5454/Toms-Storage/assets/163355234/134202c2-a90d-4109-89fc-a06af563211b)

**Comment by tom5454** [comment]
The terminal block must be within an 8 block radius of the beacon block.
You can see a beacon icon in the terminal when you are in range.

**Comment by MuseOfWorlds** [comment]
> The terminal block must be within an 8 block radius of the beacon block. You can see a beacon icon in the terminal when you are in range.

Confirmed, closing this one. It would be nice for that limitation to be listed somewhere within the mod/item/guide of some sort.

Thank you.
