### ISSUE TITLE
Items DISAPPEARED when destroying CRAFTING TERMINAL

### ISSUE THREAD

**Issue by KarboMydrates** [tom5454/Toms-Storage#334]
In fabric 1.18.2, when you put items into the crafting 3X3 box of the **Crafting Terminal** and then destroy the Terminal, the item will **disappear** when you place it back. 
The problem is especially critical when the item is really rare, such as **diamonds**. 
I hope you can revise the code such that the item will drop out when destroying the Crafting Terminal Block.
Thank you very much!

Have a nice day!

**Comment by tom5454** [comment]
Update the mod
