### ISSUE TITLE
Tom's Simple Storage crashing on server environment after attempting to interface with Create inventories 

### ISSUE THREAD

**Issue by Ficsit-Industries** [tom5454/Toms-Storage#337]
I was playing on my server with Tom's Simple Storage and Create (as well as 500-odd other mods) and was experimenting to make a Create auto-smelter that took items from the Simple Storage and automagically smelted them, but when I tried a Smart Funnel into the furnaces with a Storage Connector going into the top (to use Create's attribute filters instead of being limited to 9 filter slots) the game crashed.

Crash and Latest Log attached to issue below.

[2024-03-26-3.log.gz](https://github.com/tom5454/Toms-Storage/files/14765285/2024-03-26-3.log.gz)
[crash-2024-03-26_15.04.47-server.txt](https://github.com/tom5454/Toms-Storage/files/14765288/crash-2024-03-26_15.04.47-server.txt)

**Comment by tom5454** [comment]
The server is timing out due to a tick taking longer than 60 seconds. How many chests do you have in your storage system? Can you create a screenshot of your setup?
