### ISSUE TITLE
Wireless terminal reach setting in config doesn't work

### ISSUE THREAD

**Issue by TheDeviantCrafter** [tom5454/Toms-Storage#34]
I've set the wirelessReach setting in the config to 64, but I still need to be within 16 blocks to use the wireless terminal.

**Comment by TheDeviantCrafter** [comment]
The inventoryConnectorRange has no effect either. I suspect the config isn't being read.

**Comment by tom5454** [comment]
What version are you using?

**Comment by TheDeviantCrafter** [comment]
1.2.16
