### ISSUE TITLE
Not sure if this is a issue but I've been trying to make a storage system above the nether bedrock roof and in the End and it does not work

### ISSUE THREAD

**Issue by X3CAL** [tom5454/Toms-Storage#340]
When I made the storage system, and of course afterwards making a level 4 beacon I used an advanced wireless item and bound it. After that, I checked the advanced wireless item, it seemed to work in the dimension I made it in, however afterwards when I went to the overworld it said that the terminal was out of range which was odd. I therefore tried to make an overworld storage system then boom, I was able to access the overworld storage system in the overworld, the End and the Nether.

I want to make a storage system in the End or the Nether (haven't decided yet) because in the server I played in people like to grief and steal my loot/items :[

So yeh hopefully someone reads this and can find a solution for me thx :]

**Comment by tom5454** [comment]
You have to chunk-load your base in the nether/end.

**Comment by X3CAL** [comment]
> You have to chunk-load your base in the nether/end.

yeah I just found that out after I added chunk a loader to see if it helps, thx tho :]]]]
