### ISSUE TITLE
Crash when clicking an item recipe

### ISSUE THREAD

**Issue by muhammedesadcomert** [tom5454/Toms-Storage#345]
The game crashes when clicking an item recipe while Tom's Crafting Terminal search bar is **empty**.

Logs: https://mclo.gs/HCGOWe4

**Comment by tom5454** [comment]
Better Recipe Book's mixin is crashing.

**Comment by muhammedesadcomert** [comment]
Ok, thank you for your response, I will open this issue on the BRB's repo.
