### ISSUE TITLE
[Question] difference iventory trim vs cable & connector?

### ISSUE THREAD

**Issue by orochi02** [tom5454/Toms-Storage#349]
what exactly speaks in favour of cables instead of using trims when cables are arguably more expensive? (requires diamonds and ender pearls vs trim wood only)

**Comment by tom5454** [comment]
The inventory connector and trims connect all touching inventories. The inventory cable connector only connects the inventory it is attached to. The inventory trims only connect up to 16 blocks (by default), The inventory cables can go much further.
