### ISSUE TITLE
game was crashed when I open some chest（fabric-1.20.1）

### ISSUE THREAD

**Issue by Huantanhua** [tom5454/Toms-Storage#351]
Game was crashed when I open some chest in 1.20.1 fabric-0.15.10
[crash-reports-2024-4-24_19.40.32.zip](https://github.com/tom5454/Toms-Storage/files/15093544/crash-reports-2024-4-24_19.40.32.zip)

**Comment by tom5454** [comment]
REI is crashing, I don't think this is from Tom's Simple Storage
