### ISSUE TITLE
stacks grow every time they're picked up

### ISSUE THREAD

**Issue by LucasI27** [tom5454/Toms-Storage#355]
When I pick up an stackable item from the crafting terminal the stack size is increased by 16, as an example, if I pick up 3 redstones from the terminal I end up with 19 in the cursor and if I put it back and pick it up again, 37 and so on until 64

**Comment by tom5454** [comment]
Please post your minecraft log

**Comment by LucasI27** [comment]
Thanks for replying, recently I replaced the inventory trim blocks with inventory cables and it completely solved it somehow, couldn't reproduce since then
