### ISSUE TITLE
Ore duplication glitch with Reinforced Chests modded recipes

### ISSUE THREAD

**Issue by Landros23** [tom5454/Toms-Storage#369]
When crafting a modded chest from the Reinforced Chests mod within the crafting terminal, one set of ores used to upgrade a chest stays in the crafting grid, effectively duping the ores. As an example, when upgrading to a copper chest, the recipe requires a chest in the middle surrounded by 8 copper ingots. Once crafted, the 8 copper ingots stay in the terminal as if they were never used; when crafting multiple at once, only one set of ingots will stay.

I'm not sure if the issue is on this mod's or Reinforced Chests' end, but it does seem to be an interaction exclusive to the crafting terminal from this one. If it does end up being the latter, I'll open an issue there. I'm also not sure if this is an issue with other modded recipes.

Minecraft version: 1.20.6
Fabric Loader version: 0.15.11
Fabric API: 0.99.0

Relevant mods:
Tom's Storage (version 1.6.16)
Reinforced Chests (verion 2.4.6)

Steps:
1. Download relevant mods
2. Interact with crafting terminal
3. Use a recipe from the Reinforced Chests mod
4. Craft said recipe; ore appears to not be consumed which is incorrect

**Comment by Landros23** [comment]
Actually, this seems to be an issue with recipes involving ores being used in the crafting terminal in general. It doesn't seem consistent after playing around with making nuggets and blocks, but duplication does end up occurring.

**Comment by tom5454** [comment]
Are you sure it's duplicating? The crafting grid has auto refill, it pulls items out of your storage system. It looks like you have copper/ores in your system.

**Comment by Landros23** [comment]
Ah, you're right, I never noticed. I didn't realize that it pulls from the terminal automatically, which also explains why I've been crafting more of something than expected when holding down shift; is there a way to disable this auto refill? If not, may be a good configuration option. Regardless, I'll close this out.
