### ISSUE TITLE
Hopper only works if item is in first position inside chest

### ISSUE THREAD

**Issue by Panderine** [tom5454/Toms-Storage#37]
If the first position is empty or if the only item is in a random position inside the chest, the hopper won't take it.

Also right clicking the hopper with an iron ore block won't work, doing it with a block of coal does. This prevents using the hopper to auto burn ores from the storage to a furnace and puting the ingots back again.

**Comment by tom5454** [comment]
What version are you using?

**Comment by Panderine** [comment]
Sorry, fabric 1.1.10
