### ISSUE TITLE
[BUG] Still not work with REI when pressing 'U'/'R' in MC 1.18.2

### ISSUE THREAD

**Issue by Tidy-Bear** [tom5454/Toms-Storage#373]
### Version
- MC: 1.18.2
- Forge: 40.2.18
- Tom‘s Storage: 1.4.5
- REI: 8.4.723

### Description
When pressing 'U' or 'R', it works fine with JEI (v10.2.1.1006), but still does not work with REI. Surely, my search bar is not focused.

Not fixed even if REI Plugin Compatibilities is installed.

All things are fine in MC 1.19.2 and 1.20.1.

### Expected Result
Show REI's recipe screen after pressing 'U' / 'R' on an item in storage.

### Related Links
#114

**Comment by tom5454** [comment]
REI on Forge isn't supported on 1.18.2, It was added in 1.19 and newer.
