### ISSUE TITLE
[Feature] Make crafting grids of wireless terminal personal

### ISSUE THREAD

**Issue by Tidy-Bear** [tom5454/Toms-Storage#374]
### Description
When playing with my friends, we often disturb each other and have to wait for someone finish their crafting work, like a blocking thread :(
I know crafting grids in the crafting terminal are one of the container slots, so is it possible to make these grids personal when using wireless terminal? Or is it designed on purpose so that we have to make several crafting terminals and bind respective one?

**Comment by tom5454** [comment]
The terminal keeps it's contents when you close it.
You have to make multiple if you want to craft at the same time.
