### ISSUE TITLE
Crafting enchanted items from the storage removes enchantment from the item

### ISSUE THREAD

**Issue by JowMK** [tom5454/Toms-Storage#376]
## Issue
I observed the issue from the prominence 2 pack, where items from the MC Dungeons Weapons that normally has enchantments by default when crafting them, didn't have the enchantments.

It seems to have some sort of incompatibility with the Tierify mod that alters the item name and attributes since one item that (for some reason) didn't get the affix applied resulted in it having the enchantments that it should.

## Expected result:
The crafted item either shows the enchantment in the product slot of the crafting terminal or the enchantments gets applied once the item is crafted

## Versions
Mod version: 1.6.5
Modpack: Prominence 2 [RPG]
Modpack Version: v2.8.6hf

### Missing enchantments
1. Setup a Crafting Terminal
2. Craft [Any enchanted item from MC Dungeons Weapons/Armor]
3. Item has no enchantments in crafting interface nor in the crafted item
 
### Has Enchantment
1. Setup a Crafting Terminal
2. Craft Soul Sucker Boots from Nether Depths Update mod (Has Soul Speed 3)
3. Item shows no enchantments in the crafting interface but the item has enchantments applied

**Comment by tom5454** [comment]
The enchantments are applied with a mixin into the crafting table menu, it'll break with every other modded crafting system. This is a bug with MC Dungeons Weapons (https://github.com/chronosacaria/MCDungeonsWeapons/issues/276).
