### ISSUE TITLE
Sorting Option Defaults to Item Amount When Opening Terminal Again

### ISSUE THREAD

**Issue by arjaytigerace** [tom5454/Toms-Storage#378]
![image](https://github.com/tom5454/Toms-Storage/assets/29908562/6ad15540-f45f-4b9f-84b6-7ca3df99e9e5)
Above I sorted it by name, after closing it and opening the terminal again, it defaults to the sorting of item amount and not the original sorting I assigned, when I press descending or ascending it fixes itself to that sorting

![image](https://github.com/tom5454/Toms-Storage/assets/29908562/8fbbc888-43f0-4045-ae55-a81cbecea82f)

This is Tom's Storage 1.6.6 on Minecraft 1.20.2 with the TNP Limitless 7 Modpack

**Comment by tom5454** [comment]
Update the mod

**Comment by arjaytigerace** [comment]
It seems isolated to a world that I have on, I tested it on another world and it doesn't really show up. So I think sthis is isolated on the world that I am playing on only.
