### ISSUE TITLE
In the new Update for Tom's Storage 1.21-2.0.0 Fabric, there is no Inventory Cable Connector in the mod itself.

### ISSUE THREAD

**Issue by BannanaManz** [tom5454/Toms-Storage#381]
I downloaded the mod for the new 1.21 update and it has everything in the mod it usually does except the inventory cable connector that attaches to the chest to do the transfer of items to the terminal. Is someone able to look further into this?
![2024-06-16_21 19 53](https://github.com/tom5454/Toms-Storage/assets/147731672/ffa5e5a0-f49a-4f67-a01e-db6b9dbffb70)

**Comment by tom5454** [comment]
The 1.21 version is a rewrite, the cable connectors isn't in the game right now, it will be added back in a future update.

**Comment by AriMoon-88** [comment]
Here are the errors related to this issue from my Fabric 1.21-0.15.11 server.  Log created at server start on 22-Jun-2024.

---------BEGIN SERVER ERRORS--------------
22.06 17:08:53 [Server] Worker-Main-3/ERROR Couldn't parse element minecraft:loot_table/toms_storage:blocks/inventory_proxy - Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: toms_storage:inventory_proxy
22.06 17:08:53 [Server] Worker-Main-3/ERROR Couldn't parse element minecraft:loot_table/toms_storage:blocks/inventory_cable_connector - Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: toms_storage:inventory_cable_connector
22.06 17:08:53 [Server] Worker-Main-3/ERROR Couldn't parse element minecraft:loot_table/toms_storage:blocks/inventory_cable_connector_framed - Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: toms_storage:inventory_cable_connector_framed
---------END SERVER ERRORS--------------

---------BEGIN SERVER MOD LIST----------
GlitchCore-fabric-1.21-2.0.0.1.jar
TerraBlender-fabric-1.21-4.0.0.1.jar
appleskin-fabric-mc1.21-3.0.2.jar
worldedit-mod-7.3.4-beta-01.jar
jei-1.21-fabric-19.0.0.9.jar
journeymap-fabric-1.21-6.0.0-beta.7.jar
BiomesOPlenty-fabric-1.21-21.0.0.7.jar
fabric-api-0.100.3+1.21.jar
toms_storage_fabric-1.21-2.0.2.jar
---------BEGIN SERVER MOD LIST----------

Thanks tom5454, I love this mod!
