### ISSUE TITLE
I was playing with friends, and there simply isn't a recipe for the mod's items

### ISSUE THREAD

**Issue by Th1rty** [tom5454/Toms-Storage#382]
I was trying to play with friends on neoforge, and the recipe didn't appear, we tried to find the recipe using commands, with REI and several other ways.But it didn't work, even using the recipe from old versions, it simply doesn't craft the item. We tested it in creative, with Simple Storage being the only mod, and it still didn't work.

**Comment by Berringer** [comment]
Same here, I tried since the 1.21 update but no luck getting it to work.
Tried any recipe but can only get the items in creative.
When I click the item in REI nothing happens

Fabric v0.15.11
Sodium v0.5.9
Indium v1.0.33
REI v16.0.729
TSSM v2.0

![image](https://github.com/tom5454/Toms-Storage/assets/32061445/88bbeb64-552d-4af8-9cb4-09f4767dc02a)

**Comment by paulo-rqsf** [comment]
Still getting the same issue :(

![image](https://github.com/tom5454/Toms-Storage/assets/70488751/12905945-c1c3-472f-8da9-65914452bb9d)

**Comment by Berringer** [comment]
> Still getting the same issue :(
> 
> ![image](https://private-user-images.githubusercontent.com/70488751/340783526-12905945-c1c3-472f-8da9-65914452bb9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzQyMzIsIm5iZiI6MTcxODczMzkzMiwicGF0aCI6Ii83MDQ4ODc1MS8zNDA3ODM1MjYtMTI5MDU5NDUtYzFjMy00NzJmLThkYTktNjU5MTQ0NTJiYjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE4MDUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3Y2ZlOTAyZmI3ZGJiMDFhMjIyNjdkMWNkNDAyMTgyN2RlZjU1Zjg4Y2NkOGI1ZmY2NjExZWVmMWYzOTdjODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NO2EqDqpPTxGpF3rdsLAzPiG-rxhBrVGkD5rAI5RWMU)
> 
> Am i doing something wrong?

Wondering the same thing, what am I missing? Not getting the items, even though the recipes are there.

**Comment by tom5454** [comment]
You need a glass block in the empty slot.
Fabric API is missing a few c tags, please report it to fabric api.
These tags are missing: `c:glass_blocks/colorless`, `c:ender_pearls`

**Comment by paulo-rqsf** [comment]
Unfortunately, putting a glass block in the empty slot doesn't solved my issue

![image](https://github.com/tom5454/Toms-Storage/assets/70488751/26bf5631-4c4e-4eea-b1cf-41ac5122362b)

The recipes are there, just can't craft it. I'm going to steal from creative until I can figure out or until be solved, thank you a lot :)
