### ISSUE TITLE
Item Duplication + Other Issues with Create Belts

### ISSUE THREAD

**Issue by Jayson729** [tom5454/Toms-Storage#384]
Seems to be related to #360 and #361, however I wanted to make a new issue instead of just commenting under one of those.

I tested this on Fabric 1.20.1 using version 1.6.7 of this mod and version [0.5.1-f-build.1417](https://modrinth.com/mod/create-fabric/version/0.5.1-f-build.1417+mc1.20.1) of Create. I could not test using a more recent version of this mod because Create is not updated to 1.20.6.

[latest.log](https://github.com/user-attachments/files/15880910/latest.log)

If an inventory connector is placed next to a belt, items on the belt are treated as inside the storage system. This causes some other problems such as the ability to take items off a belt before they are actually in an inventory. However, the largest problem is this allows for duplication (although not a completely accurate term). Basically, while any item is on the belt, taking any other item out of the system will turn the item on the belt into this other item. For example, in a scenario where you have one dirt in the system and you drop one cobblestone onto the belt, taking out the dirt would result in 2 pieces of dirt and 0 cobblestone. This also applies when there are multiple items on the belt. So 1 dirt in the system and 32 cobblestone on the belt would result in 33 dirt and 0 cobblestone. Similarly, 1 dirt in the system, 1 cobblestone on the belt, and 1 granite on the belt would result in 3 dirt and nothing else.

For other people with this issue, the simple (temporary) solution is to just not have the belt touch any inventory connected to the inventory connector.

Here are some videos of the above scenarios:

https://github.com/tom5454/Toms-Storage/assets/91502167/3ed26ea9-31e5-414b-a8ae-537d57e04e48

https://github.com/tom5454/Toms-Storage/assets/91502167/45b4a801-8f08-43af-9da1-7a795c0d91e5

https://github.com/tom5454/Toms-Storage/assets/91502167/0511b4d9-1700-4e2d-b56b-b059ab37068d

**Comment by Jayson729** [comment]
Oops, duplicate of #324, didn't see that one. Would love to see a port of this fix for 1.20.1 since that is currently Create's latest version, however that's obviously up to you.

**Comment by tom5454** [comment]
This is a create fabric bug, it allows extracting without checking the item type.
https://github.com/Fabricators-of-Create/Create/blob/mc1.20.1/fabric/dev/src/main/java/com/simibubi/create/content/kinetics/belt/transport/ItemHandlerBeltSegment.java#L33-L43
