### ISSUE TITLE
Terminal doesn't put items into drawer when empty chests are available

### ISSUE THREAD

**Issue by EntityinArray** [tom5454/Toms-Storage#389]
For some reason, the mod always ignores Drawer Access Point and puts items into chests/barrels when they are available
When you withdraw diamonds from they system and put them back again, it always ignores the drawer

1. How exactly Terminal determines the inventory to put items in? Distance of inventory from the terminal seems to not affect anything.
2. Is it possible to implement priority for inventory connectors, so that player could set higher priority for Drawer Access Point?

![image](https://github.com/tom5454/Toms-Storage/assets/18554021/88f2efc0-93bc-45d0-9a47-1a139282a38c)
![image](https://github.com/tom5454/Toms-Storage/assets/18554021/62ffa512-e69c-4211-8922-e72c66298b16)
![image](https://github.com/tom5454/Toms-Storage/assets/18554021/aff68087-5729-47fe-a9c9-d33699d2e1cd)

**Comment by tom5454** [comment]
Filtered inventory cable connectors have a priority option.
