### ISSUE TITLE
[Server] Using paint kit on block puts player in kick loop.

### ISSUE THREAD

**Issue by PaulZappia** [tom5454/Toms-Storage#39]
I crafted a paint kit and right clicked on a block to select it, however I ended up getting kicked from my server, saying the connection had been lost. I tried relogging but I still got the same message. Even restarting the server didn't fix the issue.
Hopefully this can be fixed.

**Comment by tom5454** [comment]
Are you using forge or fabric?
What other mods do you have installed?
Can you check your minecraft log, and the server's log?

**Comment by PaulZappia** [comment]
I'm using the latest fabric version of the mod.
I'll try and send a log when I can since I ended up removing the paint kit from my inventory using an NBT editor.

**Comment by badcrave** [comment]
We found a similar issue to this on my server, whenever we use the paint kit to select a block with weird blockstates (in our case, mushroom blocks) and then painting the inventory cables with them. For now we have disabled the paint kit.
