### ISSUE TITLE
I can't see the item recipes

### ISSUE THREAD

**Issue by Zero000002** [tom5454/Toms-Storage#392]
I don't know if the problem is this mod or REI (Roughly Enough Items mod) but in mc 1.21 I can't see the item recipes

**Comment by Berringer** [comment]
Nah, there has been issues with this for 1.21, some tags in REI missing and such.
I've not been able to craft a single item from this mod in 1.21.
In one version the recipe worked, but no item was generated.
![image](https://github.com/tom5454/Toms-Storage/assets/32061445/d4d58665-3272-4026-a29c-86d97c177c06)

**Comment by Zero000002** [comment]
> Nah, there has been issues with this for 1.21, some tags in REI missing and such. I've not been able to craft a single item from this mod in 1.21. In one version the recipe worked, but no item was generated. ![image](https://private-user-images.githubusercontent.com/32061445/342019747-d4d58665-3272-4026-a29c-86d97c177c06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMTk2NjMsIm5iZiI6MTcxOTExOTM2MywicGF0aCI6Ii8zMjA2MTQ0NS8zNDIwMTk3NDctZDRkNTg2NjUtMzI3Mi00MDI2LWEyOWMtODZkOTdjMTc3YzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDA1MDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZjAzZTZlM2YxNGMxMWZkN2ZmMGY1Y2IzYzUzNWRiN2JkNjQ5NTVlYzY2MTU1NzM4MzAzNjAyNDUxMmQ5OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z2OHANWhYlYiGVyJKYFv6y3u_w3Z0Wxl-egC0glbhLA)

I discovered the problem, for some reason the mod menu was not notifying the new updates of this mod, it was still on version 2.0.0, v2.0.2 seems to be working correctly

**Comment by Berringer** [comment]
> > Nah, there has been issues with this for 1.21, some tags in REI missing and such. I've not been able to craft a single item from this mod in 1.21. In one version the recipe worked, but no item was generated. ![image](https://private-user-images.githubusercontent.com/32061445/342019747-d4d58665-3272-4026-a29c-86d97c177c06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMTk2NjMsIm5iZiI6MTcxOTExOTM2MywicGF0aCI6Ii8zMjA2MTQ0NS8zNDIwMTk3NDctZDRkNTg2NjUtMzI3Mi00MDI2LWEyOWMtODZkOTdjMTc3YzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDA1MDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZjAzZTZlM2YxNGMxMWZkN2ZmMGY1Y2IzYzUzNWRiN2JkNjQ5NTVlYzY2MTU1NzM4MzAzNjAyNDUxMmQ5OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z2OHANWhYlYiGVyJKYFv6y3u_w3Z0Wxl-egC0glbhLA)
> 
> I discovered the problem, for some reason the mod menu was not notifying the new updates of this mod, it was still on version 2.0.0, v2.0.2 seems to be working correctly

Ok, I've had v2.0.2 since it came, still not working, something is wrong.
Worst case scenario, building a "vanilla storage" ugh :)

**Comment by tom5454** [comment]
Make sure Tom's Simple Storage is up-to-date, the fabric versions had missing tags in the recipes, which is fixed now.

**Comment by Berringer** [comment]
> Make sure Tom's Simple Storage is up-to-date, the fabric versions had missing tags in the recipes, which is fixed now.

It is, updated just now. Tried to minimize the amount of mods too. Tried EMI, JEI, still nothing. 
Well EMI let me click the paint kit. Will put this on pause for now. Maybe a new instance can sort it.
Must be on my end.
Thank you for a great mod!

**Comment by Berringer** [comment]
The latest update, 2.0.4 (27th of June 2024) fixed all my issues, works like a gem now! Ty!
