### ISSUE TITLE
Inventory Hopper only pulls item from the first discovered inventory slot

### ISSUE THREAD

**Issue by Socn** [tom5454/Toms-Storage#396]
## Versions
Minecraft: 1.21
Fabric: 0.15.11
Mod: 2.0.3

## Setup
![2024-06-25_01 44 51](https://github.com/tom5454/Toms-Storage/assets/61719926/2b74da52-7dd4-4230-adff-e2ba57c7b440)
![2024-06-25_01 44 56](https://github.com/tom5454/Toms-Storage/assets/61719926/8b9d9e9f-86ac-41a8-a5c9-72d11041de61)
![2024-06-25_01 44 58](https://github.com/tom5454/Toms-Storage/assets/61719926/51436245-4a9d-4dff-8fb9-437702632aab)
![2024-06-25_01 45 01](https://github.com/tom5454/Toms-Storage/assets/61719926/766ee8df-6ebe-42ed-8a1b-225376476a95)
![2024-06-25_01 45 17](https://github.com/tom5454/Toms-Storage/assets/61719926/194fae65-9276-4f42-bf9d-a7ea0c99c29f)
![2024-06-25_01 45 33](https://github.com/tom5454/Toms-Storage/assets/61719926/372fe36e-0293-4c32-a36c-143bd116aa13)

As you can see, even when the furnace still has space to store more coal and raw iron, the hopper stops pulling item from the next slot (In the raw iron chest it's the third slot 'cause I didn't put any in the first slot). When I exit and log into the world again, the items in the next slot are pulled into the furnace.

So I guess the inventory hoppers will only pull items from the first slot it discovered (that passes the filter of the hopper). Is this behaviour intended or just a bug?

**Comment by Potatopatatasudo** [comment]
Same problem here!! this is desperating me, same as the inventory cable connector, it says "access denied"
