### ISSUE TITLE
Game unable to launch with the mod [Fabric] [1.0.0]

### ISSUE THREAD

**Issue by loleq2105** [tom5454/Toms-Storage#4]
My Minecraft fails to launch with the mod installed. Here's what pops up when I try launching it:
![screengrab](https://user-images.githubusercontent.com/52840858/87991594-c8e59780-cae6-11ea-901b-ec018bf6a233.PNG)
And here's my latest.log:
https://paste.gg/p/anonymous/def255cc9c4c45e6b05ff28f882ea81a

**Comment by tom5454** [comment]
The fabric version requires Tom's Fabric Lib.
https://www.curseforge.com/minecraft/mc-mods/toms-fabric-lib
