### ISSUE TITLE
[1.21 - Fabric] Advanced Wireless Terminal Not Working Across Dimensions

### ISSUE THREAD

**Issue by rainbows007** [tom5454/Toms-Storage#402]
Hello. I have an advanced wireless terminal that works everywhere in the overworld dimension, but the GUI will not open in the nether. This first image is showing what chunks I have forceloaded, and that it includes the inventory terminal and connector.

![2024-07-02_10 27 55](https://github.com/tom5454/Toms-Storage/assets/174476204/0ec0984f-12b2-49c5-be3d-2d0caa7149c2)

This image is showing I have a beacon within 8 blocks

![image](https://github.com/tom5454/Toms-Storage/assets/174476204/8b334b9a-e85a-47b9-a37f-1e69c5de0d26)

And finally, this image is showing that the terminal itself shows a level 4 beacon as active

<img width="1225" alt="image" src="https://github.com/tom5454/Toms-Storage/assets/174476204/0af19fff-cde7-4db3-babf-e9f13e453374">

I have gone 1k blocks away from the storage system in the overworld and it opens up fine. But when I go to the nether, the GUI does not open. I do not get a message that I am too far away, there is no message at all. My character just does the hand motion like it's opening but nothing comes up. This is on a server. 

It is in 1.21 using toms_storage_fabric-1.21-2.0.4.jar

Is there anything else I can check to help figure this out?

**Comment by VenomV2123** [comment]
I am having the EXACT same problem as you, and have not been able to figure it out, whether it's on a single player world or a server.

**Comment by rainbows007** [comment]
Yeah I thought it might have been some of the other mods i had, but i booted a fresh world with only this mod, tried all 1.21 jars and still had the problem. I also tried putting the storage in world spawn chunks instead of force loaded chunks in case force loading just lazy loaded the chunks and that didn't seem to work either.
