### ISSUE TITLE
Crash with Encountered an unexpected exception

### ISSUE THREAD

**Issue by Wayaans** [tom5454/Toms-Storage#406]
i got crash and error said Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.transfer.v1.storage.Storage.getVersion()" because the return value of "com.tom.storagemod.inventory.PlatformItemHandler.getP()" is null

is there someone having the same problem? idk if mod conflict or not.
thanks

**Comment by tom5454** [comment]
Please post your minecraft log

**Comment by Wayaans** [comment]
thanks for the reply, here my minecraft log

Log:
[crash-2024-07-04_23.56.32-server.txt](https://github.com/user-attachments/files/16102012/crash-2024-07-04_23.56.32-server.txt)

**Comment by tom5454** [comment]
Can you post a screenshot of your terminal that crashes?
It looks like the block behind it is pretending it has an inventory.

**Comment by Wayaans** [comment]
<img width="1587" alt="Screenshot 2024-07-05 at 22 15 52" src="https://github.com/tom5454/Toms-Storage/assets/38068544/4c148bbf-5d07-4184-9835-e03ba7c7cd15">
<img width="1577" alt="Screenshot 2024-07-05 at 22 15 32" src="https://github.com/tom5454/Toms-Storage/assets/38068544/014a2d0c-6e40-49e3-9781-d2857dce0e88">

fyi, i just trying the mod in fresh creative world, and just crash when im trying to opening the crafting terminal.

[crash-2024-07-04_23.37.04-client.txt](https://github.com/user-attachments/files/16111373/crash-2024-07-04_23.37.04-client.txt)

i attch the client report too, who know you need it, thanks

**Comment by tom5454** [comment]
What block is behing the crafting terminal?

**Comment by Wayaans** [comment]
crafting terminal stick to inventory interface
