### ISSUE TITLE
Crash on Crafting terminal open

### ISSUE THREAD

**Issue by DarkPenguinHQ** [tom5454/Toms-Storage#407]
Whenever I open my crafting terminal I crash due to a "Ticking Screen"

Heres my crash log:

[crash-2024-07-05_02.11.51-client.txt](https://github.com/user-attachments/files/16105648/crash-2024-07-05_02.11.51-client.txt)

**Comment by tom5454** [comment]
You have a broken modded item in your system, `Item:components` returns null in the item.
Try opening your chest one by one and see which crashes your game.
Hovering over or attempting to stack the item will crash the game.
Or maybe see if it crashes in the creative inventory, or in something like JEI.

**Comment by DarkPenguinHQ** [comment]
Ive tried all of those, the only thing that crashes is when i open up the crafting terminal.

**Comment by DarkPenguinHQ** [comment]
it seems to work fine when i use individual inventory cable connectors, and not just the inventory connector by itself?

**Comment by DarkPenguinHQ** [comment]
nevermind^^

**Comment by DarkPenguinHQ** [comment]
I figured it out, there were 16 universal trade shops with different configs
