### ISSUE TITLE
(Suggestion) Update infinite range/add new block for substitution 

### ISSUE THREAD

**Issue by LoveOrLogic** [tom5454/Toms-Storage#411]
While in public servers, force load is not accessible. I know many others have had the same issue in regards to something like this, so please make it so this feature is not chunk dependent if possible. If that is not possible, then at least add an item that lets you connect terminals without the long ass pipe. Something I can just place down and have instant access to my terminal back at base. Ofc it should be more of an end game item, but it will at least be better than not being able to enjoy arguably one of the best features of the mod

**Comment by tom5454** [comment]
You can place an inventory cable connector on a beacon to create a remote link. The Inventory cable connector has all of the details in the item tooltip. You give the connector a name i the UI and every other connector with the same name connects.

The mod stores items inside your chests, which must be loaded to access or modify, there is no way around that.

**Comment by LoveOrLogic** [comment]
But it can work for mods that have a portable ender chest with access
needing just a click of a button. Cables don't bring it to other dimensions
either.
