### ISSUE TITLE
[1.21] [Neoforge] Crafter Bug: deleting items and not showing recipes

### ISSUE THREAD

**Issue by ffuentesm** [tom5454/Toms-Storage#413]
When I click on the fill recipe, or shift click on an item fill the recipe, the planks get deleted from the inventory, as if they were pulled but they are not. Even if I try to pick planks from the inventory screen, they are deleted when I click it. 

Also, the "craftables" tab is glitching on EMI, not showing anything unless I am holding an item on my cursor

toms_storage-1.21-2.0.5
Neoforge 21.0.81
emi-1.1.10+1.21+neoforge
jei-1.21-neoforge-19.5.0.30

![image](https://github.com/user-attachments/assets/884d310d-1d86-413f-b09c-6bbddabd465b)
![image](https://github.com/user-attachments/assets/6ab18f38-c2af-479e-b3f3-6f5ff255e8bb)
![image](https://github.com/user-attachments/assets/6cfba578-e47b-42d6-a3b9-0e665ba66377)
![image](https://github.com/user-attachments/assets/334d1184-399e-4c33-93e0-71c886128ce1)

**Comment by tom5454** [comment]
I don't see any item loss.
I fixed the craftables menu in the latest update,

**Comment by tom5454** [comment]
Please reopen if this issue still exists in the latest release.
