### ISSUE TITLE
1.21 filters/pipes not working.

### ISSUE THREAD

**Issue by Gharsnull** [tom5454/Toms-Storage#414]
So first, Guide posted on mondrith is outdated I think. 

Filtered inventory cable connector doesnt exist anymore, instead it says to use the inventory configurator to filter it. 

so I set up an scenario simmilar to what is shown on Guide video on minute 4:45 https://www.youtube.com/watch?v=nW5ElcWiC3c.

https://github.com/user-attachments/assets/574b0acd-16f4-40d7-887e-cf9b874af9ac

**Comment by Gharsnull** [comment]
For instance if I remove the filter in the midlle inventyory cable connector, is still doesnt bring the remaining items from the source chest

**Comment by ffuentesm** [comment]
Yeah, the guide no longer works for 1.21, specially since a lot of functions were added to the Inventory configurator, which I have no idea how to use it. 1.19/1.20.1  versions were way more simple and straightforward to understand and use.
