### ISSUE TITLE
(non-portable temrinals) (1.21 fabric) items flashing in and out of existence

### ISSUE THREAD

**Issue by ggezgaming** [tom5454/Toms-Storage#418]
as the name suggests when looking at the terminal items will constantly flash in and out of existence as if the storage network was constantly being recognized and then forgotten. Minimizing amount of entities connected to the network fixes nothing.

**Comment by tom5454** [comment]
Can you post a screenshot of your setup?

**Comment by tom5454** [comment]
Duplicate of #420
