### ISSUE TITLE
[1.21][Neoforge] Crafteting terminal still not reconising inventoryu for available crafts recipes

### ISSUE THREAD

**Issue by ffuentesm** [tom5454/Toms-Storage#419]
neoforge: 21.0.95
toms_storage-1.21-2.0.6
emi-1.1.10+1.21+neoforge
The available crafting window in EMI is only showing items that are in my inventory, and also, the items are not even craftable as I do not have half of the required items in those recipes. 
![image](https://github.com/user-attachments/assets/62ce84be-a759-4069-b31f-94f6ddb985d1)

As you can see, the items in red show that I lack that item, I don;t even have in inside the terminal
![image](https://github.com/user-attachments/assets/50131dc3-ca81-441e-9ce7-8dc4622c0e5f)
![image](https://github.com/user-attachments/assets/b529ab8a-8c67-4bff-baab-0097b6c115d2)

**Comment by tom5454** [comment]
Fixed in the latest release
I added a smart toggle under the search setting, which toggles if the terminal contents are included in EMI's Craftables item list (can cause frame lag with 10k+ items)
