### ISSUE TITLE
Storage and Crafting Terminal do not work on MC 1.21 Fabric (SERVER)

### ISSUE THREAD

**Issue by Knito58** [tom5454/Toms-Storage#423]
SMP on a Fabric server with Fabric API 0.100.7 on MC 1.21. TSSM 2.0.7.
Right clicking on the storage connector shows the correct amount of connected devices. There are even some resources shown in the Jade-tip.
However, when connecting the crafting terminal to the connector it just stays empty. Same with connection cable.

I used this mod in SSP and there it just worked fine. The problem seems to be the server part. There is no crash. Do you still want latest.log?

![2024-07-20_17 02 53](https://github.com/user-attachments/assets/6aaa3953-cc45-4544-85d3-20e4a912469f)
![2024-07-20_17 02 39](https://github.com/user-attachments/assets/18446900-f9a2-4eb0-bae4-b59036cae04b)

**Comment by pkyios** [comment]
Im having the same problem, but im playing on single player mode and its bugged. Crafting and Storage Terminals are not working at all.

**Comment by Knito58** [comment]
I just see there is a new version 2.0.8 from today. @pkyios can you test it?

**Comment by pkyios** [comment]
> I just see there is a new version 2.0.8 from today. @pkyios can you test it?

tested it right now, works like a charm.

**Comment by Knito58** [comment]
Yay! I'll update my client and server modpacks and report here.

**Comment by Knito58** [comment]
It still not works on server. Now with TSSM 2.0.8, both on client and server. The screenshots with the empty GUIs still apply. I cannot close this issue.
:(

**Comment by Knito58** [comment]
I can shift click stacks into the left crafting terminal. They are not seen there, the GUI still stays empty. However, the items are stored savely into the storage system and can be found when clicking through all the chests.

**Comment by tom5454** [comment]
You no longer need the Inventory Cable Connector behind the terminal, that won't work anymore in 2.0.0 updates.
You can just place the terminal on an inventory cable.

**Comment by Knito58** [comment]
Thank you. The one that reacted to shift clicking was the one directly applied to the storage connector cube. I removed the other crafting terminal. The inventory cable connector did not have a default tool when removing it, i noticed.

**Comment by Knito58** [comment]
After re-checking server files: I did not really update the 2.0.7 version. It was still there.
So: All is my fault. Sorry for insisting on a non existant bug: 2.0.8 did fix it, also in multi player.
