### ISSUE TITLE
Incorrect item count!

### ISSUE THREAD

**Issue by Nitroito** [tom5454/Toms-Storage#426]
When i open Storage Terminal
![S  Terminal](https://github.com/user-attachments/assets/cbca2534-4b44-4dd8-9a42-9bee42b76ebb)

When i open Crafting Terminal
![C Terminal](https://github.com/user-attachments/assets/32c34c75-4bcc-4b37-a49e-21d3cb84dddc)

the crafting terminal is duplicating the item count

Minecraft Version: Fabric 1.21
Mod Version: 2.0.8

i am using also Stackable Mod

**Comment by ffuentesm** [comment]
You need to use the Inventory Configurator and merge the double chests into a single inventory 
![image](https://github.com/user-attachments/assets/5b743f1d-2726-475d-b23a-15d8f75c6db5)
![image](https://github.com/user-attachments/assets/6e35f8e9-baec-4161-9346-c65242ebe25d)
This way it stop the item duplication.

**Comment by Nitroito** [comment]
the issue i found is releated to Inventory Connctors... for each connector adjacent if multiplies te count!!

eg: 3 Inventory connectors placed side by side and you have 10 potatos on 1 chest... the terminal will show 30 potatoes.
