### ISSUE TITLE
1.16.4 Basic Inventory Hopper ALOT of MS Lag

### ISSUE THREAD

**Issue by F0gboy** [tom5454/Toms-Storage#43]
Basically, the basic inventory hoppers start to lag alot after a while (1500 MS each) Dropping the server TPS by 5-7 TPS, i saw there was this issue at an earlier date, but it seems it still occurs.

**Comment by xanthian** [comment]
I also have noticed this, using observable profiler they are the items causing the most lag on the server, more-so than normal hoppers.
This only occurs when the inventory they are trying to place in to is not full, full inventories are much lower (presumably as the hopper is no longer activ
![hopper lag](https://user-images.githubusercontent.com/7688001/137541840-bedb4eb6-a282-4d85-8e89-92e9cb924caf.jpg)
e)
