### ISSUE TITLE
Latedest update won't work.

### ISSUE THREAD

**Issue by deadpool772** [tom5454/Toms-Storage#430]
after installing the latest files toms_storage-1.21-2.0.7.jar the in game mods list dosen't show a version number only 0.0NONE, and i cant craft any of the items or spawns them in

![Screenshot (9)](https://github.com/user-attachments/assets/4fbedae2-565f-47ac-8db3-9af92f49f510)

![Screenshot (12)](https://github.com/user-attachments/assets/d4c8593d-9173-4e4c-8abe-32ba127fa1ac)

**Comment by tom5454** [comment]
Please post your minecraft log
The version number is currently bugged, but it should work.
