### ISSUE TITLE
2.0.8 unable to craft items added from mod

### ISSUE THREAD

**Issue by deadpool772** [tom5454/Toms-Storage#433]
I am unable to craft any of the items added by Tom's simple storage. i can however access them in crative and spwan them in but the recipes dont work. 

![2024-07-28_16 30 03](https://github.com/user-attachments/assets/3d7524e1-d7be-44f2-b2e8-2b84f38f3417)

![2024-07-28_16 30 45](https://github.com/user-attachments/assets/4e24fee4-abb8-4ba5-874c-00256c122734)

![2024-07-28_16 31 08](https://github.com/user-attachments/assets/763e392f-5375-410b-a7f9-319d4c4c6db2)

[latest.log](https://github.com/user-attachments/files/16405550/latest.log)

**Comment by deadpool772** [comment]
[debug.log](https://github.com/user-attachments/files/16405553/debug.log)

**Comment by tom5454** [comment]
Try removing all of your other mods, I can't reproduce it with a clean install of NeoForge 21.0.143.

**Comment by deadpool772** [comment]
made a new installation on forge with only tom's storage installed

[debug.log](https://github.com/user-attachments/files/16405906/debug.log)
[latest.log](https://github.com/user-attachments/files/16405907/latest.log)
![2024-07-28_17 41 34](https://github.com/user-attachments/assets/f0729779-8a2f-4b24-8be1-061737e543fa)

**Comment by deadpool772** [comment]
![Screenshot (13)](https://github.com/user-attachments/assets/b6a60c4b-9c6e-4040-9198-b4d659fe8109)

**Comment by Parker101200** [comment]
Also having this issue as of 9/5/24
