### ISSUE TITLE
Create item vault displaying different storage amounts depending on whether it's empty

### ISSUE THREAD

**Issue by MaxWasUnavailable** [tom5454/Toms-Storage#434]
1.20.1 Forge

See screenshots for showcase of the issue / confusion:

![2024-08-01_07 32 07](https://github.com/user-attachments/assets/8b9b7490-9d4f-41de-855b-34446a3ede87)
![2024-08-01_07 32 23](https://github.com/user-attachments/assets/733d888f-3c00-46e8-a530-a694fc11eb81)
![2024-08-01_07 32 34](https://github.com/user-attachments/assets/fa3e4cf3-4269-4865-815f-3f65c5b8f659)

**Comment by tom5454** [comment]
The mod has an "Inventory Deduplicator" to prevent counting the same item multiple times with multiblock containers (Create Vault).
It only works when there are items in the inventory.
