### ISSUE TITLE
[1.21][Fabric]Advanced Wireless Terminal & Trinkets

### ISSUE THREAD

**Issue by Suifulv** [tom5454/Toms-Storage#438]
Advanced Wireless Terminal did not apply to Trinkets for a belt slots，so it cannot be equipped in cosmetic slots.

**Comment by schmitzrj** [comment]
Will trinkets still be supported in 1.21? I searched the repo and it looks like there is just a dummy file, probably added while waiting for Trinkets to get updated for 1.21, but that's been updated for a while now. Thanks for the great mod!
