### ISSUE TITLE
Crash while setting up storage network

### ISSUE THREAD

**Issue by AlisterGontineac** [tom5454/Toms-Storage#44]
https://gist.githubusercontent.com/natanfudge/002741a4e827d0856477e25b4c8263b1/raw/0c7b688805aeab19951bcdce0b82ffd0f240b2ef/crash.txt

Can't go back into my world now. I was setting up a network, left the game to back up my save because I had been working on it for a while, then when trying to go back in, I crashed, and it won't let me load back in.

**Comment by tom5454** [comment]
Please try the latest version 1.1.12

**Comment by AlisterGontineac** [comment]
Thanks, worked
