### ISSUE TITLE
Storage- / Crafting-Terminal show double amount of items

### ISSUE THREAD

**Issue by fabiobaser** [tom5454/Toms-Storage#45]
If you connect double chests to an inventory connector the amount of items is wrongly shown double the amount.

E.g. you have 1 Book in a double chest but the storage terminal shows 2.

On verion 1.1.1.1 with 67 other mods. The error occurs even with only the storage mod present.
Fabric Loader 0.11.6

**Comment by tom5454** [comment]
This was fixed in 1.1.12 of Tom's Storage
