### ISSUE TITLE
Tom's simple storage

### ISSUE THREAD

**Issue by TigerKrempl** [tom5454/Toms-Storage#450]
playing on cruseforge custom mod account. when i click on the crafting terminal game stops. nothing moves, cant open chest, break blocks cant place blocks nothing. no crash report, game doesnt crash. But cant close it. In task manager uses all allocated RAM.

**Comment by TigerKrempl** [comment]
forgot to include  when opening the terminal its shows as all the chests are empty

**Comment by ffuentesm** [comment]
What launcher? Which Version are you using? Any other Mods?

**Comment by TigerKrempl** [comment]
im playing on 1.21 minecraft java version, fabric - 0.16.2.
other mods inlcude:
- additional structures by XxRexRaptorxX
- advanced music mod 
- alloy forgery 
- animal feeding trough
- Architectury API 
- artifacts
- athena
- better advancements
- better recipe books (+smithing tables, brewing stands)
- Biomes O' plenty
- blasting raw metal blocks into blocks
- cardinal components API
- Carry on
- Charm of undying
- Chipped
- Chipped express
- Cloth Config API
- Clumps
- Cobweb
- Collective
- Compostables
- CraftTweaker
- Cristel LIB
- Croptopia
- Cupboard
- Dungeons and Taverns
- Durability Tooltop
- Dynamic Lights
- Elytra slot
- EpheroLib
- Explorify - Dungeons & structures
- fabric API
- Faux custom entitiy data
- Fish of thieves
- Forge Config API port
- GeckoLib
- GlitchCore
- GObber
- handcrafted
- Harvest with ease
- InventoryTweak
- Jade
- JamLib
- Just Enough Items
- just Hammers
- Lan Server Properties
- Lavender API
- Macaw's bridges
- Macaw's bridges - BIomes O' plenty
- Macaw's doors
- Macaws's fences and walls
- Macaw's furniture
- - Macaw's lights and lamps
- Macaw's Paths and Pavings
- Macaw's roofs
- Macaw's trapdoors
- Macaw'swindows
- MaLiLib - community updated
- ModernFix
- Mouse Tweaks
- mythic metals
- Mythic Upgrades
- Nature's compass
- oritech
- owo-lib
- Phillips Ruins
- Polymorph
- Reborn Core
- Resourceful LIb
- retraining
- RightclickHarvest
- Searchable
- spark
- Structory
- SuperMartijn642's Config lib
- Tech reborn
- Terrabelnder
- Towns and Towers
- Traveler's Backpack
- tree harvester
- Trinkets
- Useful hats
- Xaero's minimap
- Xaero's World map

**Comment by TigerKrempl** [comment]
Solution: i had mini automatic bonemeal farm connected to chest and terminal crashed it. Removed the farm it works fine now.
