### ISSUE TITLE
Crash when opening terminal with many chests

### ISSUE THREAD

**Issue by Emerald-Fox** [tom5454/Toms-Storage#457]
I've skimmed through the log and it seems to just be this mod causing the crash, it didn't crash before when I only had a few chests connected. 
[crash-2024-08-24_02.29.19-client.txt](https://github.com/user-attachments/files/16735583/crash-2024-08-24_02.29.19-client.txt)

**Comment by tom5454** [comment]
You have a broken item inside your storage system. Somehow the default component list of the item is null. If you can please open your inventories one by one and hover over each item individually. Some modded item will crash. Similar to #407.

**Comment by Emerald-Fox** [comment]
Just wanted to add, I did some testing and I've pinpointed that items from this mod are the culprit [https://modrinth.com/mod/polydecorations](https://modrinth.com/mod/polydecorations), it's entirely server side added blocks and doesn't require to be installed client side, that's possibly why it causes a crash
