### ISSUE TITLE
Crash when installed with Vivecraft Compat

### ISSUE THREAD

**Issue by BroBoss64** [tom5454/Toms-Storage#464]
When loading client with both mods it crashes. 1.20-1.6.8-fabric
[crash-2024-09-21_17.14.49-client.txt](https://github.com/user-attachments/files/17085884/crash-2024-09-21_17.14.49-client.txt)

**Comment by tom5454** [comment]
Fixed in https://github.com/tom5454/ViveCraftCompat/commit/16fef7c2e018097927fd6da46ca59d390f966e5e
