### ISSUE TITLE
Toms simple storage mod not working properly

### ISSUE THREAD

**Issue by Arion199** [tom5454/Toms-Storage#475]
The mods items appear in JEI but they have no recipes and cannot be crafted. In creative mode they disappear immediately after being placed and cannot be interacted with. I have attached the mods list below as there may be an incompatibility im unaware of.

Kind regards
Arion
![Screenshot 2024-10-19 001812](https://github.com/user-attachments/assets/bff3fa86-490e-4f6b-9cba-91f67619af64)

**Comment by Phoz0226** [comment]
Did you ever find a solution? Im having a very similar issue.
