### ISSUE TITLE
Search does not include tags

### ISSUE THREAD

**Issue by Grand-Ben** [tom5454/Toms-Storage#484]
When I do a search for a category or tag such as food or weapon, the result  is only items with that search term in the attributes or description of the item.  When  another person on the server searches using my terminal, they get a different result that includes everything tagged with the search term.  
I've included screenshots of  a search for weapon, and a chest in the system that definitely has weapons in it.  

I'm using version 3.0.10
Minecraft version 1.20.1

I was rather disappointed and a bit confused when I learned that the other person on the server got different results than what I got. 

I have no idea if it's significant, but when I use the  terminal window, the color of the font  is different than when the other person on the server uses his or my terminal.  Mine is orange, there's is black.

![Screenshot_2024-11-10_11-27-00](https://github.com/user-attachments/assets/a7832a31-5aae-45ff-9645-5edd0c66d025)
![Screenshot_2024-11-10_11-23-50](https://github.com/user-attachments/assets/9a2a6f26-39cb-42a7-95fb-9f8329fb4424)

**Comment by tom5454** [comment]
You can tag search by typing `#food`.
