### ISSUE TITLE
Quirky inventory sync issues with 1.1.13 for Fabric on MC 1.17.1

### ISSUE THREAD

**Issue by Danklor** [tom5454/Toms-Storage#49]
This may affect more than this case, but here's what I saw in single player.  After accessing a storage network with a crafting terminal on an inventory connector connected to a number of adjacent barrels, when breaking a block and picking it up it did not show in my inventory.  It didn't show up until I clicked inventory items around or dropped pick it up again at least once.  An instant fix is to close the world and reload.

There is no crash and nothing at all shows in the log.

**Comment by Mattabase** [comment]
This happens in 1.16.5 and 1.17 as well, this can be repeated by closing the terminal using anything other than the inventory open/close key

**Comment by MSandro** [comment]
I realy hope this can be fixed soon.
