### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by damphon** [tom5454/Toms-Storage#5]
Hey, thanks for making this mod! When using the crafting terminal if I type anything into the terminal I get no results. Even if I type the full name of the item.

**Comment by tom5454** [comment]
Are you using forge or fabric?

**Comment by lostdutchman** [comment]
I'm using Forge.

**Comment by tom5454** [comment]
Are you using 1.15 or 1.16?

**Comment by lostdutchman** [comment]
1.16

**Comment by tom5454** [comment]
Fixed in the latest release

**Comment by damphon** [comment]
1.16
