### ISSUE TITLE
Most items from the Relics mod cannot be extracted using the crafting/storage terminal

### ISSUE THREAD

**Issue by TuckV** [tom5454/Toms-Storage#52]
I have no way of knowing if this is a bug in Tom's Storage or Relics but most items from Relics cannot be extracted from inventories with Tom's Storage. (1.2.16)

Edit: I did some testing and found that Lore Fragments from Enigmatic Legacy also cannot be extracted by Tom's Storage.

**Comment by flippy1345** [comment]
I can add that servos from Industrial Revolution cannot be extracted, but at this point only this one item.
Server logs don't show any error.
