### ISSUE TITLE
Inventory Connector shows incorrect information

### ISSUE THREAD

**Issue by SharkieTV** [tom5454/Toms-Storage#56]
Hi, I saw someone else mention this but I found a different bug.
Version Tom's Storage 1.2.16 added to [Better Minecraft Modpack](https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack)

When placed like this the inventory shows correctly 
https://i.imgur.com/acAWMVX.png
https://i.imgur.com/72EbC67.png
https://i.imgur.com/Y1htlIW.png

When placed like this it doubles the amount of items
https://i.imgur.com/K1hJClb.png
https://i.imgur.com/YjcpR5d.png
https://i.imgur.com/ALVtSNj.png

**Comment by Wedge1453** [comment]
happens with all multi-block containers, it shows (real amount)*(container block size) of items stored in that container, thankfully it's visual only, doesn't actually double items, but still it's a bug.
![2021-08-06_10 00 21](https://user-images.githubusercontent.com/76813383/128486441-2cfd4b58-0a76-4bad-b56c-4f65ac6d97f8.png)
