### ISSUE TITLE
Frozen at terminal search

### ISSUE THREAD

**Issue by red2blue** [tom5454/Toms-Storage#59]
latest version of toms storage
1.17.1 
fabric

![image](https://user-images.githubusercontent.com/35115304/132955933-363306f6-58a8-4c93-a8c4-488a5664b5f6.png)

When using terminal search, it gets stuck here and cannot exit.

**Comment by FreeFull** [comment]
Assuming this is the same issue I'm experiencing: The terminal works perfectly as intended, except there doesn't seem to be any way at all to quit out of it (Esc doesn't work).
