### ISSUE TITLE
Issue FABRIC: Paint makes block invisible

### ISSUE THREAD

**Issue by TheRisingUnited** [tom5454/Toms-Storage#61]
Painting a block makes it invisible instead of painting it to be the correct block

**Comment by BaronSolace** [comment]
can confirm.   to reproduce just paint something. anything

**Comment by Kuli222** [comment]
I have the same problem :-(

**Comment by pelletstove** [comment]
I can confirm the same issue

**Comment by loanenems** [comment]
Can confirm it too. Occurs on server

A simple working fix is to update the surrounding blocks, it worked for me
