### ISSUE TITLE
Unable to remove some items from terminal

### ISSUE THREAD

**Issue by jcianca** [tom5454/Toms-Storage#63]
Running fabric 1.17.1 - Tom's Simple Storage 1.1.15. Also manually updated to try it on 1.1.16 (Curse forge defaults to 1.1.15) and the issue persists in both versions. 
Cannot remove: 
Ukulele from Artifality
Zeus Staff from Artifality (sometimes)
Forest Staff from Artifality
Lithium Battery from Tech Reborn

No errors, just nothing happens when I click these specific items. I can go into the barrel directly and remove them like normal, they just don't seem to work with the terminal.

**Comment by Jacob345k** [comment]
I'm still having this issue, forge 1.18.2. Random items, tom's cables, and some vanilla items too.
