### ISSUE TITLE
Pulling items from one chest to another unfiltered.

### ISSUE THREAD

**Issue by Sublime204** [tom5454/Toms-Storage#67]
When trying to move items dropped into a chest to a chest for my smelter unfiltered using the Basic Inventory Hopper set to pull from the first chest and an Inventory Cable Connector on the chest at my smelter with a Inventory Connector in between I'm able to get it to pull from only one slot of the first chest but if I put multiple items in different slots it will only pull from the 1 however if I filter 1 single item using the Hopper on the smelter side it will pull that item from any slot. I've tried a number of different configurations but I cannot find a way to pull from all slots without using a filter.

Using version 1.2.18 on Forge 1.16.5

**Comment by xanthian** [comment]
Can replicate this issue on Fabric version also,
Using unfiltered hoppers to pull from storage (chests, normal hoppers, etc..) it will only ever take from the 1st slot
