### ISSUE TITLE
Items are shown with double the amount

### ISSUE THREAD

**Issue by Entharia** [tom5454/Toms-Storage#77]
When placing anything into the storage it will be shown with double the amount.

Minecraft Version: 1.18
Fabric Version: 0.12.12

I connect my chest via trims and 1 connector.
I tested this with normal chests and it is the same issue so i dont think the iron chests are at fault here
![2021-12-27_11 29 57](https://user-images.githubusercontent.com/59421695/147463091-f6512cda-0e14-4ea8-841e-63f81bb01ab2.png)

**Comment by Satont** [comment]
Same here.

**Comment by hughjass11** [comment]
I'm having same problem with the double chests showing double but when I make them all single chests they show correct.amount

**Comment by tom5454** [comment]
Duplicate #69
