### ISSUE TITLE
Invisible crafted items until clicked and crafting is completed

### ISSUE THREAD

**Issue by Nerdtality** [tom5454/Toms-Storage#79]
Crafted items are invisible in the crafted slot until you click on it to finish crafting.

Toms Storage 1.1.19
MC 1.18.1
Fabric 0.12.12

![image](https://user-images.githubusercontent.com/19711169/148143481-bc488df9-897a-497c-b6e7-70fe2fbc0085.png)

**Comment by Damien13150** [comment]
Same problem here

Minecraft : 1.17.1
Toms storage : 1.1.18
Fabric : 0.12.12
