### ISSUE TITLE
wireless terminal issues

### ISSUE THREAD

**Issue by Dragonracer1973** [tom5454/Toms-Storage#80]
The original wireless remote does not show inventory upon which it is connected. The upgraded version does (netherite). The second issue is the wireless remote will not hold the config for the range of it. I am including a screenshot of the config file as I have it set, and the in-game config after restarting instance. I am using version 1.1.19 of the mod ![image](https://user-images.githubusercontent.com/50302305/150219322-188ba9fb-5b10-422c-b6c5-f37f00647e82.png)

**Comment by tom5454** [comment]
The range has a limit of 512, anything over that will reset it back to the default value.
The original wireless terminal only extends your reach to the terminal. You have to click on the terminal to open it.
