### ISSUE TITLE
Advanced Wireless Terminal Out of Range Message

### ISSUE THREAD

**Issue by dpill83** [tom5454/Toms-Storage#86]
I changed advWirelessRange seting from 64 to 256 in toms_storage.json. Restarted the server and used the Advanced Wireless Terminal 128 blocks away from the terminal, I can access the connected terminal but the message "Terminal out of range" still appears.

![image](https://user-images.githubusercontent.com/35717779/160735510-a6d9aecd-37ab-4b2b-bdca-4a93286db8e3.png)

**Comment by tom5454** [comment]
Couldn't reproduce with latest versions.
