### ISSUE TITLE
[1.16] Crafting with Shift Stops Short of Max Stack

### ISSUE THREAD

**Issue by HenryMaxler** [tom5454/Toms-Storage#87]
Hello, I am loving the mod, but a couple things seemed like issues:

1. Crafting with shift to craft the maximum amount stops 1 short of the maximum stack size.  For example, if you shift craft planks it makes 60.  So if you want to craft a stack, you have to click twice.  With iron buckets you only make 15 at a time instead of 16.
2. When I'm looking in JEI and want to click back to the Crafting Terminal screen, sometimes I missclick on the search bar and start typing only to find it's not inputting.  I'm not sure if it's a glitch but I would suggest considering making a wider area for clicking to reactivate the search bar.  Maybe the whole area of the gui.  Edit: tried out other modes and they had issue when using "r" and "u" keys when mousing over JEI or the inventory part.
3. After typing in a search, once it is deselected, the text remains but the _ underscore disappears.  If you wish to clear the text and enter something else, you can right click the bar.  But after doing this sequence, the search bar is not selected so you have to left click first.

**Comment by tom5454** [comment]
Was fixed in 1.18 and 1.19 versions, 1.16 is no longer supported.
