### ISSUE TITLE
1.16.1 - Cannot Replicate Mod Spotlight Configurations

### ISSUE THREAD

**Issue by JoshMayberry** [tom5454/Toms-Storage#9]
Wonderful mod! I am very excited to use it in my world!
Unfortunately, there seem to be some issues when I follow the designs in the mod spotlight on the main page.
Instead of making a separate issue for each one, I put them all here (hope that's ok).

### All Mods in the mod folder for this test
 - tomsstorage-1.1.0.jar
 - fabric-api-0.14.1+build.372-1.16
 - RoughlyEnoughItems-4.8.1
 - modmenu-1.12.2+build.17

## No Double Chest Support
If an _inventory cable connector_ is placed on one side of a double chest, only the items in that side are detected:
![image](https://user-images.githubusercontent.com/11482252/88465542-e40f2900-ce91-11ea-95f7-906503675770.png)
![image](https://user-images.githubusercontent.com/11482252/88465600-67c91580-ce92-11ea-9121-a1d4c4014b8a.png) ![image](https://user-images.githubusercontent.com/11482252/88465583-40724880-ce92-11ea-892d-a68133b6a8c9.png)

To see both sides of the chest, two connectors are needed:
![image](https://user-images.githubusercontent.com/11482252/88465634-9f37c200-ce92-11ea-9df4-516753a61aa2.png)
![image](https://user-images.githubusercontent.com/11482252/88465677-b676af80-ce92-11ea-8c0c-0d89e8320ec1.png)

The mod spotlight suggests this should not be the case:
![image](https://user-images.githubusercontent.com/11482252/88465701-d9a15f00-ce92-11ea-891f-223a3a35fee8.png)

## Connectors Do not Chain
This set up from the mod spotlight does not work, only the left side of the bottom chest is accessable via the terminal:
![image](https://user-images.githubusercontent.com/11482252/88466339-44ee2f80-ce99-11ea-8832-2e3066f5ecdb.png)

And this set up cannot see any thing, because there is no chest connected to the first connector:
![image](https://user-images.githubusercontent.com/11482252/88466356-78c95500-ce99-11ea-9ccf-57c4c8e912b6.png)

## Cannot Access After a Connector
If a _storage terminal_ is placed on an _inventory connector like this, the terminal can access the inventory:
![image](https://user-images.githubusercontent.com/11482252/88465794-c93db400-ce93-11ea-88a9-c7e5fa26d3ac.png)

But if it is connected after the terminal like this, it cannot access the inventory:
![image](https://user-images.githubusercontent.com/11482252/88465854-6ef12300-ce94-11ea-904a-67a87f846f2f.png)

The mod spotlight suggests this should not be the case:
![image](https://user-images.githubusercontent.com/11482252/88465871-b24b9180-ce94-11ea-8a6f-393be91c0a02.png)
![image](https://user-images.githubusercontent.com/11482252/88465924-fccd0e00-ce94-11ea-8973-9937e9fde1ac.png)

## No Loop Detection:
If I follow this part of the mod spotlight block-for-block, no loop detection message shows up- the inventory just flickers back and forth between a low and high number.
![image](https://user-images.githubusercontent.com/11482252/88466082-d60fd700-ce96-11ea-8a04-caf270caded6.png) 
![image](https://user-images.githubusercontent.com/11482252/88466435-30f6fd80-ce9a-11ea-86a0-a7a33ff4c3c8.png)

## Proxies can Misrepresent Items
If a chest is connected to a proxy and the network, it's contents will be counted incorrectly:
![image](https://user-images.githubusercontent.com/11482252/88466023-32bec200-ce96-11ea-8569-d2d33e2ff038.png)
![image](https://user-images.githubusercontent.com/11482252/88466042-67cb1480-ce96-11ea-999e-aa8197f9b848.png)
![image](https://user-images.githubusercontent.com/11482252/88466050-79acb780-ce96-11ea-880d-e9d1c0d72c05.png)

**Comment by tom5454** [comment]
The latest version sould fix most of the bugs.
The connectors don't chain, you have to use Inventory Trims for chaining.
